### ISSUE TITLE
[DK2] SteamVR won't load PS3EYE or Move controllers if Oculus is running

### ISSUE THREAD

**Issue by pejmany** [cboulay/PSMoveService#101]
My second ps3eye finally came in the mail so I decided to set it up (on your conveniently released alpha4.3). 

I think the oculus runtime is interfering with the driver load in. 

When I run psmoveservice then steamvr while oculus is running, I get no complaints from psmoveservice but steamvr only shows the oculus tracker and dk2. 

When I force stop oculus vr services/processes steamvr actually recognizes the two ps3eyes and two move controllers. 

Here is [vrserver.txt](https://github.com/cboulay/PSMoveService/files/349262/vrserver.txt) associated with each. 

edit: I tried it out with the current 4.4 alpha, and I still have the same result.

**Comment by HipsterSloth** [comment]
From the log it looks like it's trying to load the 32-bit version of the drivers. Are you running on a 32-bit or a 64-bit version of windows? If 64-bit I would expect to SteamVR to load the 64-bit drivers (assuming you have the latest build of SteamVR. If you launch steamvr and then look at process viewer which folder is vrserver.exe running from: bin/win32 or bin/win64?

**Comment by pejmany** [comment]
Vrserver.exe is from the win64 folder. I read on here that the cleyemulticam dll doesn't work with 64 bit, so I only have one camera connected for this one. 

This 
[vrserver.txt](https://github.com/cboulay/PSMoveService/files/351407/vrserver.txt) is from running the win64 psmoveservice. 

In the steamvr/driver/psmove there's only the win64 drivers.

**Comment by HipsterSloth** [comment]
I don't see any mention of the psmove drivers in the most recent vrserver.txt. 

Do you still have the following in your steamvr.vrsettings file?
```
   "steamvr" : {
      "activateMultipleDrivers" : true,
```

Did you have PSMoveService.exe running the background when you launched steamvr?

Also you can use cleye multicam dll in 64-bit steamvr, but you have to run the 32-bit PSMoveService:
1) Run PSMoveService\Win64\bin\SteamVR_ReinstallDriverWin64.bat
  -> This copies over the 64-bit driver into steamvr/driver/psmove (which is sounds like you have done)
2) Run PSMoveService\Win32\bin\PSMoveService.exe
  -> Since PSMoveService talks to steamvr over the network it can be a 32-bit program (that loads the 32-bit cleye dll) but talks to a 64-bit program (\win64\vrserver.exe)

**Comment by pejmany** [comment]
I just checked the vrsettings and activate was set as active. I must have messed up when I reinstalled steamvr. thanks!

Although now the oculus isn't working. Nor withh the move controllers turn off. I'll comment after the restart.
