### ISSUE TITLE
MSVC 2015 build broken in steamvr_64-bit branch

### ISSUE THREAD

**Issue by hawkinse** [cboulay/PSMoveService#104]
With the streamvr_64bit branch, I am able to successfully build 32-bit debug and release builds, as well as a 64-bit release build. However, 64-bit debug builds fail on PSMoveMath where I get the following in my build output: 

`2>C:\Users\Elliot Hawkins\Documents\src\PSMoveService\src\psmovemath\MathAlignment.cpp : fatal error C1128: number of sections exceeded object file format limit : compile with /bigobj`

I've added /bigobj as suggested to the command line options for PSMoveMath, but it appears that doesn't resolve the issue. This is on Windows 10 with Visual Studio 2015. [If it helps, here is a complete copy of my build output.](http://pastebin.com/eDc2XAb7)

**Comment by HipsterSloth** [comment]
Ah! I actually hit this issue myself yesterday. We want to migrate to 2015 but I haven't gotten past this issue, as well as a few others yet. If you want to build this branch, you'll have to do it using 2013 for the moment. I'm going to try and get this working in 2015 in the next few days though.

**Comment by HipsterSloth** [comment]
@hawkinse Also, if you manage to get the build working in 2015 before I get a change to fix it, let me what you had to tweak. You would be my hero.

**Comment by hawkinse** [comment]
Thanks, 2013 works. Probably should have tried that first. If I figure anything out regarding 2015 I'll post here.

**Comment by hawkinse** [comment]
Commenting out various sections of MathAlignment.cpp, I found the issue to be in the function eigen_alignment_fit_least_squares_ellipse. In particular, line 390:

`Eigen::EigenSolver<Eigen::Matrix3f> eigsolv(Mout);`

It's the call to EigenSolver's constructor that is preventing 2015 from compiling. Replacing that line with a declaration only allows PSMoveMath to compile, although obviously it wont function.

**Comment by cboulay** [comment]
I swear I've used Eigen on MSVC 64-bit before.

In this fix I'm not quite there yet because I ran into a problem even earlier than that. When I updated libusb and opened its MSVC2015 project in MSVC2015, it wouldn't build because it said I was missing the v140 toolset (i.e. the toolset that comes with MSVC2015). I'm reinstalling now, but my Windows PC at work is on some pretty terrible wifi. It won't be done before I go home today.

**Comment by cboulay** [comment]
@hawkinse Can you please try #108 ? I just built 64-bit debug PSMoveMath with MSVC2015 on my machine. The thing that was missing was a flag to tell MSVC to let the math object be big (compiler flag `/bigobj`), because the 64-bit debug symbols are big.

This branch expects OpenCV 3.1 and libusb 1.61, and OpenCV 3.1 precompiled binary download only comes with 64-bit Release binaries. @HipsterSloth has added OpenCV 32-bit Debug/Release steps to InitialSetup_Win32.bat, but we don't yet have steps for OpenCV 64-bit Debug build. In other words, for now at least, you have to cmake && build OpenCV3.1 yourself if you wan to use x64-debug.

**Comment by hawkinse** [comment]
@cboulay PSMoveMath builds fine with [#108](https://github.com/cboulay/PSMoveService/pull/108). I also see now that I was attempting to setting /bigobj incorrectly. Sorry about the misleading post with Eigen.

**Comment by cboulay** [comment]
@hawkinse No problem. I tried several times to get cmake to set that flag correctly. I would love to have set it for debug builds only but that proved impossible. I generally dislike setting compiler flags directly because you never know what else is in the list that you might be stomping or over-written by, so I try to use cmake's native commands as much as possible. But in this case I didn't find one that worked.

**Comment by cboulay** [comment]
There's a commit in master that handles this. Also our other branches that change the build system handle this as well. Closing.
