### ISSUE TITLE
"Failed to start controller stream" error when starting Calibrate Tracking Colors

### ISSUE THREAD

**Issue by ToppestOfDogs** [cboulay/PSMoveService#112]
I've followed the instructions on the wiki and watched a video, but I get stuck at the color calibration. I can't find any mention of this error.

**Comment by cboulay** [comment]
Can you please verify that your controller is paired and connected? e.g., try doing the magnetometer calibration.

**Comment by ToppestOfDogs** [comment]
Yes it is paired and I have done the magnetometer calibration. I've followed the steps on the wiki in order but I can't get past color calibration.

**Comment by HipsterSloth** [comment]
Does the controller still show up in the list of connected controllers? Also the controller isn't connected via USB still right? That error only happens if the config tool can't get a controller data stream from the service and that would only happen if the service didn't have a valid bluetooth controller connected. 

Also would you mind attaching your PSMoveService0.log file?

**Comment by ToppestOfDogs** [comment]
Okay it suddenly started working today.

**Comment by cheddle** [comment]
A reboot usually sorts this out for me and only happens again when I add / change the camera driver/usb port.
