### ISSUE TITLE
Notify SteamVR when the hmd_tracking_space settings and camera poses change

### ISSUE THREAD

**Issue by xMindweaverx** [cboulay/PSMoveService#113]
I have 2x PS Eyes and every time I use the Calibration Mat my controllers and cameras are 4 to 6 feet above my head. I don't have positional tracking on my HMD. So, I'm just using "Standing". I've tried changing the z axis in "_C:\Users\<username>\AppData\Roaming\PSMoveService\Controller_mac_address.json_" but nothing changes. Where can I manually change these values. I would also like to be able to rotate the cameras because they are about 30 degrees off to the left.

Also, since the past few updates I only have one controller (_I'm using the x64 build_). I hate to have so many questions, but I'm at my wit's end.. hehe You guys have done an amazing job and I thank you for making this even possible.

**Comment by zelmon64** [comment]
The simple solution would be to place the calibration mat 4 to 6 feet lower but I realise that may not be possible. Try re-running room setup and changing the height you input for the HMD. What HMD are you using? If it's VRidge then you can adjust the height using FreePIE to send the data via FreeTrack.

Do you have SteamVR running when you calibrate because this could effect the co-registration.

Without seeing the logs it's hard to think why you only have one controller. Is the red LED stable on you second one?

**Comment by xMindweaverx** [comment]
Aww, I never thought of placing the calibration mat lower. So, the cal mat should really be used on the floor or closer to it. I have both of my cameras on the left and right side of my desk using tripods and they are set to round 6 feet. I need to put them higher and point them more to the ground. I'm currently using my dk1. I have a freefly that I use with my Galaxy s6, but I prefer the dk1 due to less lag. So, would the .json file I listed above for the controller not be where I need to change the z axis? If I understood the configuration files a little better then I would be more than happy to start working on a tool in Visual Studio to manually adjust those settings.

I can work through the controller issue. I was just wondering what changed. I can get it back by unpairing both controllers and then re-pairing them again. Wait.. just a thought, but whichever controller I pair first.. Should this be the controller I turn on first everytime? Plus, to turn off my controllers I unplug my bluetooth adapter. Thanks for your help @zelmon64!

**Comment by zelmon64** [comment]
I haven't looked into that .json file so I don't really know how it works but @HipsterSloth will be able to tell you later. Since you're using a dk1 how are you getting head movement?

You should only have to pair the PSMove controllers once. To turn them off simply hold the PS button for >10s (if a client is running it may complain/crash). It should not matter which you turn back on first. To let the computer know that the controllers are disconnected I usually disable my bt in the device manager (because otherwise they disrupt the controller I use for Kodi for some reason).

Is the controller not reconnecting to windows or is it just not seen in SteamVR? Do you use the new pairing function in the configuration tool or the original programs?

**Comment by HipsterSloth** [comment]
You can adjust the the y-axis (y is up in steamvr and in psmove service) in the '
TrackerManagerConfig.json' config file. Look for the 'hmd_tracking_space' section and adjust the y-value there. That position and orientation is the hmd position and facing in steamvr's coordinate system of the hmd when centered facing forward 
on the calibration mat. I'be been meaning to document the config files but have been swamped with trying finish features of the service. Sorry it's so opaque right now. If you do create a manual offset tool i'd prefer it go in the config tool client, but if you want to write a quick standalone thing to edit the json file that's fine too.

As for the controller dissappearing, is it not even in the controllers list in the config tool or just in game? If it's only in game this is a steam vr issue that happened in the most recent update. Valve tweaked how controller roles worked and it broke hand assignment for games using the default unity steamvr vr plugin. The fix for that will be in the next steamvr beta. Details are in issue #94

**Comment by xMindweaverx** [comment]
Thanks @HipsterSloth ! I'll change the Y axis in '_TrakermanagerConfig.json_'. I downloaded VS 2013 yesterday. If I do make anything I'll add it to the config tool client. When I grabbed the project earlier I only had 2015 installed at home and 2010 and 2015 at work.  No need for apologies this is shaping up nicely and well worth the wait. it really baffles me at the lack of companies not trying to create controllers for hand presences. You would think Razer would update their Hydras, but they are planing to use a 3rd party glove.. but yea I think my controller issue is just from the latest update, because windows sees both motion controllers and so does the config tool. I was just wanting to verify. Thanks again for the speedy response!

@zelmon64 I'll start disabling it in device manager. I'm suprised at how well the config tool tracks it. It would be cool to add an led strip to the front for tracking or something close to the PSVR. Thanks for your help!

**Comment by HipsterSloth** [comment]
@xMindweaverx FWIW we're in the middle of making psmoveservice compile with MSVC 2015. There is a [2015 branch](https://github.com/cboulay/PSMoveService/tree/msvc2015_64bit) that is almost ready. Hopefully that will be pushed up to master by the end of this week.

**Comment by xMindweaverx** [comment]
@HipsterSloth changing the y axis in "_orientation_" didn't change the height. Decreasing the value rotated everything to the right. 

Here is my file content.
`{
    "version": "2",
    "default_tracker_profile": {
        "exposure": "56",
        "gain": "56",
        "color_preset": {
            "magenta": {
                "hue_center": "150",
                "hue_range": "20",
                "saturation_center": "80",
                "saturation_range": "97",
                "value_center": "245",
                "value_range": "32"
            },
            "cyan": {
                "hue_center": "90",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "yellow": {
                "hue_center": "30",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "red": {
                "hue_center": "0",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "green": {
                "hue_center": "60",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            },
            "blue": {
                "hue_center": "120",
                "hue_range": "10",
                "saturation_center": "255",
                "saturation_range": "32",
                "value_center": "255",
                "value_range": "32"
            }
        }
    },
    "hmd_tracking_space": {
        "orientation": {
            "w": "0.910448611",
            "x": "0",
            "y": "0.41362223",
            "z": "0"
        },
        "position": {
            "x": "-10.1344433",
            "y": "3.16747022",
            "z": "17.1889973"
        }
    }
}
`

**Comment by HipsterSloth** [comment]
Oh sorry I should have been more clear. You want to modify the y value in the "position" section, not the orientation. The orientation value is a [quaternion](https://en.wikipedia.org/wiki/Quaternion) used to define the rotation of the tracking space and almost certainly not what you want to tweak.

**Comment by xMindweaverx** [comment]
Ok I don't know what's going on, but I changed the y axis in "position" and both trackers and controller are behind me at the same height.

**Comment by HipsterSloth** [comment]
Huh. I could have sworn we were using the OpenGL coordinate system where +Y is up. Try the "z" value instead. Sorry for the guess work.

**Comment by xMindweaverx** [comment]
z axis didn't do anything. I'm closing SteamVR and then the PS Move Service then I'm editing the .json file with Notepad++. Then I'm starting the service and then steamvr. I've changed x, y, z values in "position" and non of those lower the cameras or the controller.

**Comment by HipsterSloth** [comment]
Hmm. Have you tried recalibrating your head hight in the Oculus settings? Does the dk1 even work in oculus home at this point? I'm kind of out of obvious things to try. I might just have to try and repro this at home, but it''s going to be this weekend at the earliest before I can get to that.

**Comment by xMindweaverx** [comment]
Yea, I'm recalibrating it now. I'm currently using Oculus runtime 0.8. I'm going to mess around with it a little bit more tonight. If I figure out anything I'll let you know tomorrow. Thanks again!

**Comment by xMindweaverx** [comment]
So, I didn't get far last night before I ran out of gas... lol I plan to recalibrate tonight. I just seen your "_Manual psmove tracking color calibration_" video @HipsterSloth on Youtube. You should link to those videos in your Wiki. I think my calibration is off. I backup my "_C:\Users<username>\AppData\Roaming\PSMoveService\_" folder often. The best setup I had previously was when I calibrated during the day and had more light in the room. Reloading that backup made a big difference. I also raised my Trackers up to around 7' from 6'. I'm 6'4" so I wanted the trackers above my head.

Also, this morning I notice about an hour after I went to bed Steam released a new SteamVR beta. I hope this one fixes the controller issue.

**Comment by HipsterSloth** [comment]
Thanks for the heads up about the steamvr update. I'll check to see if that fixed the hand issue.

Your comment about the config backups reminds me, I want to add a feature for saving multiple color calibration profiles (daytime, nighttime, etc).

As for videos we actually have someone polishing up a setup tutorial video now that's much better than the quick test videos I made.

**Comment by xMindweaverx** [comment]
No problem. I look forward to the video. I wrote this:

If you have **WinRAR** copy and paste the below into a text file and save to desktop and then set the extension to ".bat". Then double click the file to execute. <-- _This is for anyone that doesn't know._
`@echo off

:: variables
set tt=%time:~0,2%_%time:~3,2%_Backup
set BackupLocation="%~dp0\PSMoveService_Backup"
set backup="%BackupLocation%\%date:/=-% %tt%.rar"
set Saveme="%USERPROFILE%\AppData\Roaming\PSMoveService"

IF NOT EXIST %BackupLocation% mkdir %backuplocation%

"%programfiles%\winrar\rar" a -ep %backup% %Saveme%

@pause
::echo ### Finished on %date% %time%
::echo Backup Complete!`

If you don't have **WinRAR**
`@echo off
:: variables
set BackupLocation="%~dp0\PSMoveService_Backup"
set Saveme="%USERPROFILE%\AppData\Roaming\PSMoveService"
set tt=%time:~0,2%_%time:~3,2%_Backup
set folder=%date:/=-% %tt%
set backupcmd=xcopy /s /c /d /e /h /i /r /k /y


color 9F
echo ### Mindweaver's Backup Plain

%backupcmd% "%Saveme%\*.*" "%BackupLocation%\%folder%\%file%"

:: Comment the next 2 lines below if you don't want to set attributes.
echo ### Setting Attribute's
attrib +r -h %BackupLocation%\* /s /d

echo This Backup was created on Date (%date%), Time (%time%). >> "%BackupLocation%\%folder%\Backuplog.txt"

echo Backup Complete!
@pause`

**Comment by xMindweaverx** [comment]
Ok more testing tonight and was able to get both controller working. When I manually set the controller colors I was taking the the other one out of calibration. I didn't realize the left side (_Color Calibration_) is one setting for all colors. The only settings that you can save with each color are the settings on the right side (_Controller Calibration_). So by changing the Color Calibration settings on the second color I was taking the 1st color out of calibration... Now I just set the Color Calibration that works for both colors (_1st Magenta, and 2nd Cyan_). Then I set the Controller Calibration and save the settings for both colors. Now both controllers are in SteamVR and Games.

So, next Controller and Tracker height. I changed the Y setting and still I don't see any changes.  Next I tried changing the Z axis and still nothing. It's crazy because moving my hmd up or down causes the controllers and camera to raise and lower the same offset difference. It's as if the HMD is on the floor and the controllers and camera are at the right height, but in the holodeck like in SteamVR my HMD is off the ground correctly. I've tried doing the Calibration Mat with the HMD on the floor. I have Steam VR Standing set to 76" and I even tried putting it to 0" and my HMD is in the floor. I'm wondering in the TrackermanagerConfig.json for orientation which of the 4x (_w,x,y,z_) is the HMD height and which is for controller Height? Can you post your hmd tracking space settings @HipsterSloth ? Mine are below.

```
"hmd_tracking_space": {
        "orientation": {
            "w": "0.855038047",
            "x": "0",
            "y": "0.518565297",
            "z": "0"
        },
        "position": {
            "x": "-11.2541981",
            "y": "3.22888947",
            "z": "20.2555428"
        }
    } 
```

**Comment by HipsterSloth** [comment]
Here is my tracking space settings:

```
    "hmd_tracking_space": {
        "orientation": {
            "w": "0.999944746",
            "x": "0",
            "y": "0.0105108134",
            "z": "0"
        },
        "position": {
            "x": "28.3204651",
            "y": "-41.3078918",
            "z": "31.3759708"
        }
    }
```

Also important point about this:

> I'm wondering in the TrackermanagerConfig.json for orientation which of the 4x (w,x,y,z) is the HMD height and which is for controller Height?

None of the 4 values (w,x,y,z) in the "Orientation" block have anything to to do with HMD height or controller height. Allow me to explain...

SteamVR has one tracking coordinate system whose origin is somewhere relative to your HMD tracking camera. PSMove Service has it's own completely independent coordinate system whose origin and facing you define with the calibration mat. In order to get the psmove controllers in the same coordinate system as steam VR we have to know where the two coordinate systems are relative to each other. The "orientation" and "position" of the "hmd_tracking_space" are the position and rotation of your HMD in steamVRs coordinate system when it's placed at the center of the calibration mat facing forward during the last step of the tracking setup tool.

So in my calibration data above when a psmove controller is placed at the center of the calibration mat, it's actually at x=28.3204651, y=-41.3078918, z= 31.3759708 in steamVR's coordinate system (units in centimeters). 

As I mentioned before, the "orientation" is a rotation stored as a quaternion, where:

 * w=cos(angle/2)
 * x=rotation_axis.x * sin(angle/2)
 * y=rotation_axis.y * sin(angle/2)
 * z=rotation_axis.z * sin(angle/2)

Or about a 70 degree rotation about the y-axis in the case of my setting.

The thing that confuses this further is that steamvr actually has multiple coordinate systems. The steam vr coordinate system I was just referring to is actually the "steamvr raw device coordinate system". When you define your room calibration, you actually create a new "standing coordinate system" that's relative to "raw device" system. 

So what's making this confusing is that you have two knobs your's adjusting that are interfering with each other, the tracker settings file and the steam vr standing height.

I would say it's probably easiest to just set the standing height to zero and only play with the "position" y-value tracking settings file, but as you said, that wasn't working for you. You are restarting steamvr each time you change the  tracking settings file right? PSMoveService doesn't currently notify steamvr when the "hmd_tracking_space" settings change (though I plan on fixing this).

**Comment by xMindweaverx** [comment]
Aww, ok that clears things up a bit for me.  Also, with those numbers at the 9th decimal place I was making really small incremental moves.. Thinking most of the adjustment was in the decimal place. I never took my Y axis below "-6.16747022" and that was only when I was frustrated... lol So, it was probably moving but not enough for me to see it in space. 

I'm ready to go home and try it using your setting of "-41.3078918". My orientation is close to yours so that makes me feel better. 

I was going to ask if you could put a rest button or button that calls the form load. Now the other frustrating this is now I can't just unplug my hdmi cable and re-seat it to clear SteamVR's "_steamvr compositor is not available_" error. This happened a couple updates back. Do you know of another method to clear that error other than restarting the PC? Thanks again!

**Comment by HipsterSloth** [comment]
> I was going to ask if you could put a rest button or button that calls the form load

Yeah I definitely want to do that. In fact I'll re-label this issue as such for tracking purposes.
> Also, with those numbers at the 9th decimal place I was making really small incremental moves.. Thinking most of the adjustment was in the decimal place.

Oh ha! Yeah with the units being in centimeters any digit smaller that then second decimal place is just noise. At some point I really need to write up some docs explaining what the values mean in the configuration files. 

>  Now the other frustrating thing is now I can't just unplug my hdmi cable and re-seat it to clear SteamVR's "steamvr compositor is not available" error.

That's a new issue to me. It's possible that the one of the steamvr processes is getting stuck running and is stuck not reconnecting to the vrcompositor process. Maybe try looking in process explorer and make sure none of the steamvr processes are still running (vrcompositor, vrserver, vrdashboard) after shutting down steamvr?

**Comment by xMindweaverx** [comment]
Nice! Yea, it would be nice to maybe add just a comment in the file it self only for people that tinker around with the config file. I don't think that part really needs to be apart of the Wiki so not to confuse people that never plan to edit that file directly.

I have killed every steam process and nothing to fix the compositor issue in SteamVR. But it just hit me that there use to be a feature in SteamVR to reset the HMD and in the beginning when you disconnected and re connected the hdmi cable you still had to reset the HMD in SteamVR. I don't know what they changed but it was really nice being able to just reconnect the hdmi to resolve that issue.. and honestly it could have been an update for windows or on the Nvidia driver that changed. I'll look tonight to see how windows is seeing the HMD (_Main or Extended_). If it's setting it to Extended then I'll try to set it to Main. Thanks again!

**Comment by xMindweaverx** [comment]
Okay, so check it out. I had to set my "Y" axis to "-150.000000000". It floored me when I set it to "-41.000000000" and it didn't look like it change at all. I then set it to "-120.000000000"... and I had movement! It actually was below my head for the first time. Sorry, for the excitement, but I just had to share my success!.. lol

**Comment by brendanwalker** [comment]
This feature request was made moot by the addition of the SteamVR start+select alignment.
