### ISSUE TITLE
Mouse Emulation, make PS Move Service control mouse to FPS Games

### ISSUE THREAD

**Issue by andregm3** [cboulay/PSMoveService#116]
![cdsdcsdc](https://cloud.githubusercontent.com/assets/4154732/16826177/6e2b63e4-4951-11e6-96df-5be36ac00aad.png)
Please make it emulate the Mouse to play FPS Games, also assign each button to keyboard and mouse keys.

**Comment by HipsterSloth** [comment]
@hawinse Is this possible to do with your FreePIE bridge that you wrote? 
https://bitbucket.org/hawkinse/psmovefreepiebridge

I've never used FreePIE myself, but I get the impression the whole point of that tool is for remapping controller input and making other virtual controllers.

@zelmon64 I think you've done something like this before with a virtual xbox controller in FreePIE?

**Comment by andregm3** [comment]
at 2:40: https://www.youtube.com/watch?v=K76wP2dxBks

**Comment by hawkinse** [comment]
@HipsertSlot @andregm3 The location of the mouse can be controlled with FreePIE, just need to write a python script that keeps track of the last known location since FreePIE's mouse handling expects deltas. It won't do button handling though, since the IO plugin I'm using only supports location and rotation.

**Comment by cboulay** [comment]
I played a lot of Killzone3 with my psmove. It was actually an advantage compared to regular controller. I wasn't great at the game but I often did well in multiplayer.

Anyway, I can tell you that it won't work for most games. It'll only work for games that allow the crosshairs to move independently of the view. There are 2 ways I've seen this implemented:

* A zone in the middle of the screen where the crosshairs are free, then the screen will rotate in the direction of the crosshairs when they are towards the edge of the screen (like Killzone3)
* Camera is on rails and you're free to aim anywhere on screen (like Time Crisis, House of the Dead, etc)

Please give me an example of a PC game with that mechanic. Also, be sure that the mechanic isn't only for some peripheral (e.g. light gun) but also works with mouse-controlled crosshairs.

Finally, I won't do this myself, but after the CAPI is done it shouldn't be too difficult for someone else to come along and write a client app that does what you want. I think it'll need a custom app because what you'll want to do is create a "virtual screen" that's at the same location, size, and resolution as your real screen, then return the controller's aim-vector's intersection with the screen as the cursor position.

**Comment by cboulay** [comment]
Actually, I wonder if this kind of mechanic already exists in VR inside steam's theatre-thing that it uses to play flat games in VR. That's how it works for operating the desktop from within SteamVR, but I've never tried a flat game where you can click on various parts of the screen.

Anyone know?

**Comment by hawkinse** [comment]
@HipsterSloth @andregm3 I added button support to my FreePIE bridge. The IO plugin only supports position/rotation, but I can send multiple position/rotation structs at a time so I store the button information as a 0 or 1 across two extra structs.  Kludgey, but it works. 

I've also added an example script showing how to use it for mouse control. Trigger is left click, Move button is right click and square is middle click. FreePIE is capable of mapping to the keyboard as well, so you can set any button on the move to any keyboard or mouse key you want.

**Comment by andregm3** [comment]
@cboulay  we add mouse look and the developers start building over it, unity, UE4 any mouse + FreeTrack do headtrack, maybe some mods to add to games, i saw a guy made it work in HalfLife:

**Comment by cboulay** [comment]
It's the opposite of "mouse look". You want "(look-)decoupled aiming" or "deadzone aiming" or something like that.

Apparently Arma 2 has deadzone aiming.

I seriously doubt a developer will add support for this kind of aiming just for PSMoveService users if they didn't already add it for the Hydra users, or for the WiiMote users, or for any other 3D controller users.

It's not relevant for VR for obvious reasons. Except that maybe some "flat" games will start supporting this kind of input if it's used through SteamVR's in-vr theatre mode.

I think your best bet is to find games or mods that already have this kind of mechanic. Arma2 and HL2's mod are certainly interesting.

But this kind of input might also be an interesting way to use a PC generally, even outside of FPSs. e.g., using it as a pointer on a projected screen on a wall.

**Comment by andregm3** [comment]
For Sure ! like painting: https://www.youtube.com/watch?v=VBAAbVSqGng

**Comment by andregm3** [comment]
This Guy made this app to mouse but only works in Windows 7 i think.

http://osvaldojr.com/moveforpc.zip

![moveeon](https://cloud.githubusercontent.com/assets/4154732/16826750/4df9f9d2-4956-11e6-99a0-e0983188c0ce.png)

**Comment by andregm3** [comment]
it works ! thanks: https://www.youtube.com/watch?v=GZDKzf5OtOM

should we calibrate something now ?

**Comment by andregm3** [comment]
Another video example of PS Move in Action now on PSVR trail game: https://www.youtube.com/watch?v=r3p7R4_9MJo

**Comment by andregm3** [comment]
https://www.youtube.com/watch?v=BkBrwHkI-CQ

**Comment by cboulay** [comment]
Mouse emulation (like Hydra emulation) would have to be handled by an external client. I'm closing this issue.

@andregm3 You are invited to make a Wiki entry about how to emulate mouse (and separately, Hydra) using PSMoveService.
