### ISSUE TITLE
When launching PSMoveService, svchost memory skyrockets before getting boost::interprocess::intermodule_singleton initialization failed

### ISSUE THREAD

**Issue by javaJake** [cboulay/PSMoveService#127]
I understand C++ fairly well and wanted to start debugging, but the setup process was a little more than I have time for. I'm reporting this issue now with ideas, and I may get time to look into this more later.

Following the latest setup in the "The Official PSMoveService Tutorial" (July 20th), I got all the way to running PSMoveService, and received this output:

```
[2016-07-21 18:46:38.639493]: main - Starting PSMoveService
Config file name: "C:\Users\jacob\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
[2016-07-21 18:46:38.645444]: bluetooth_get_host_address - Failed to find a bluetooth radio
Config file name: "C:\Users\jacob\AppData\Roaming\PSMoveService\TrackerManagerConfig.json"
[2016-07-21 18:46:38.783433]: PS3EyeTracker::open - Opening PS3EyeTracker(USB\VID_1415&PID_2000\8\0, camera_index=0)
ps3eye::PS3EYECam::getDevices() found 1 devices.
Config file name: "C:\Users\jacob\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b2_p3.2.4.json"
Config file name: "C:\Users\jacob\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b2_p3.2.4.json"
Config file name: "C:\Users\jacob\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b2_p3.2.4.json"
[2016-07-21 18:46:42.641063]: SharedMemory::initialize() - Allocating shared memory: tracker_view_0
[2016-07-21 18:46:42.644569]: EXCEPTION - PSMoveService - boost::interprocess::intermodule_singleton initialization failed
Config file name: "C:\Users\jacob\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
[2016-07-21 18:46:42.651081]: SharedMemory::dispose - Failed to free shared memory: tracker_view_0
[2016-07-21 18:46:42.653085]: ClientConnection::stop - Stopping client connection id 0
```

I noticed that svchost memory jumped dramatically, maxing out my available memory, just before "SharedMemory::initialize" printed... which seems odd. Wouldn't the debug message print before attempting to allocate memory? Maybe the console isn't printing fast enough? The memory is immediately freed after the errors print.

My first guess is that the math on how much shared memory is needed is wrong, but I presently have no way to debug this yet. :(

**Comment by javaJake** [comment]
I should add that I'm on Windows 10 Build 14393, 64-bit. I have one PSEye camera and two Move controllers.

**Comment by HipsterSloth** [comment]
Hmm I wonder if you're hitting a problem similar to issue #89. I'm pasting my response to that issue here:

" ...That said I just did a bit of googling for that exception and I found this:

'So as far as I get from internet problem may occur when boost::interprocess failed to get temporary directory on Windows as it's use following registry key by default: 
Code:
SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders\Common AppData

It's may occur when user modify registry with tools like CCleaner, but can be fixed by system reboot. It's should be possible to bypass that problem by setting "BOOST_INTERPROCESS_SHARED_DIR_PATH" so boost store shared memory in some other directory on Windows.'

I opened regedit and found the "SOFTWARE\Microsoft\Windows\CurrentVersion\Explorer\Shell Folders\Common AppData" registry key. It pointed at C:\ProgramData. I looked in there and there was the following folder C:\ProgramData\boost_interprocess\1466482908 containing a tracker_view_0 and tracker_view_1 files.

See if that registry key exists on your machine. If it does, go to the folder it specifies. If you're running win10 it almost certainly is also C:\ProgramData. Then if you have a C:\ProgramData\boost_interprocess folder, delete the files in there. My bet is the interprocess state in there is borked and deleting them will create new ones with valid state."

I'm hoping deleting the state in the boost_interprocess folder fixes the issue for you. I have no idea why the memory would skyrocket like that. It's just suppose to allocate enough space for a video frame buffer (about 1.2megs).

**Comment by javaJake** [comment]
I also found that issue and it didn't fix my problem. I will try BOOST_INTERPROCESS_SHARED_DIR_PATH later tonight. I suspect it has something to do with the large memory consumption prior to the crash.

**Comment by HipsterSloth** [comment]
Sadly I don't have time to look into this myself for the next week. I'm swamped trying to get the DualShock4 tracking well for work. But since you mentioned having exposure to C++, if you happen to feel comfortable trying to build this yourself I can outline the path that I would look down.

I allocate the shared memory here: 

https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/View/ServerTrackerView.cpp#L49-L70. 

Nothing too crazy going on there (that immediately pops out at me). The only thing I can think of is if the video buffer size (width or stride) is getting some garbage uninitialized value and try to allocate some crazy huge amount of memory. Those video frame dimensions come from here:

https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/View/ServerTrackerView.cpp#L399

Since the only camera available is the PS3Eye you must be getting the video frame dimensions from PS3EyeTracker::getVideoFrameDimensions() which is implemented here:

https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/PSMoveTracker/PS3EyeTracker.cpp#L340-L396

Since you had this line in your log: "PS3EyeTrackerConfig_ps3eye_b2_p3" that says that you are using the libusb based ps3eye driver, which means you are using the PSEYECaptureCAM_PS3EYE implementation of cv::IVideoCapture. The getProperty() method that's giving you your video frame dimensions comes from here:

https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/PSMoveTracker/PSEye/PSEyeVideoCapture.cpp#L278-L305

That internal ps3eye capture instance comes from the PS3EyeDriver submodule. It looks like the constructor for that doesn't initialize the width or height values, but the call to eye->init() won't return true unless in any case where the dimensions aren't set. So it's not clear to me that that uninitialized variables are the culprit here either:

https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/PSMoveTracker/PSEye/PSEyeVideoCapture.cpp#L400-L413

**Comment by javaJake** [comment]
Thanks for the tips! I am going to get all the dev tools configured on my gaming PC and start tinkering as soon as I can. It goes without saying that I can't promise progress. :)

**Comment by javaJake** [comment]
Wow. I have no idea why, but after going through all the work of setting up the dev environment, the original alpha4.5 binary works. I'll keep an eye on it.

There may be a KB installed by VS2013 or VS2015 that fixes something? I don't know.

**Comment by HipsterSloth** [comment]
Interesting. I should try running PSMoveService on a machine without VS installed and see if that repro the issue.

**Comment by cboulay** [comment]
I just assembled a new PC. I decided to test out alpha release 4.5 before I installed any development software. The only thing I installed on my system other than Windows 10 were hardware drivers and Google Chrome. It worked fine for me without any crashes, memory spikes, or any other obvious problems.

**Comment by HipsterSloth** [comment]
Thanks for testing that @cboulay! Glad to hear that the service works on a freshly installed machine. 

It just occurred to me that if the memory spike happened before SharedMemory::Initialize it might be boost::interprocess::shared_memory_object::remove() doing something weird. I should add some logging before and after that call. If this happens again at least we can pinpoint where the memory spike is occurring.

**Comment by masterchop** [comment]
Did you had the log to pin point this type of problems? after windows 10 update with new features, i got the following error:

`Config file name: "C:\Users\Extreme Tech\AppData\Roaming\PSMoveService\PS3EyeTrackerConfig_ps3eye_b3_p4.json"
[2016-10-06 00:01:26.480]: SharedMemory::initialize() - Allocating shared memory: tracker_view_0[2016-10-06 00:01:26.482]: EXCEPTION - PSMoveService - boost::interprocess::intermodule_singleton initialization failedConfig file name: "C:\Users\Extreme Tech\AppData\Roaming\PSMoveService\ControllerManagerConfig.json"
[2016-10-06 00:01:26.488]: PSMoveController::close - Closing PSMoveController(\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&03d5&col01#8&8c88af4&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})[2016-10-06 00:01:26.492]: PSMoveController::close - Closing PSMoveController(\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&03d5&col01#8&3532d354&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})[2016-10-06 00:01:26.495]: PSMoveController::close - Closing PSMoveController(\\?\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&03d5&col01#8&a484602&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})[2016-10-06 00:01:26.500]: SharedMemory::dispose - Failed to free shared memory: tracker_view_0[2016-10-06 00:01:26.502]: ClientConnection::stop - Stopping client connection id 0
D:\UnityStuff\PSmove-eye\PSMoveService-v0.9alpha5_2_0\Win64>`

I tried to delete the file shown in the error but it was auto-regenerated with the same data.

**Comment by HipsterSloth** [comment]
Are you running CCleaner? Check out the troubleshooting steps here:

https://github.com/cboulay/PSMoveService/wiki/Troubleshooting-%28Windows%29#getting-exception---psmoveservice---boostinterprocessintermodule_singleton-initialization-failed-in-the-logs

**Comment by masterchop** [comment]
no, i only have install unity3D, visual studio, oculos games, no oculus home, steam.  This started after windows update. psmove4unity still catch the controllers. the camera feed works just fine with all cameras.  Not sure what to do. any other type of logging

**Comment by masterchop** [comment]
is working now, no changes, no idea what happen.
