### ISSUE TITLE
Windows application?

### ISSUE THREAD

**Issue by Imgonnawork** [cboulay/PSMoveService#128]
I think would be good to add a simple application (is just for windows so will be easy) to start the service (maybe with console inside application) check the service status and stop it, without having to open folders and bat files all the time...
That's would be good for users!

Good Work
Adriano.

**Comment by HipsterSloth** [comment]
Totally agreed. This is actually part of the plan (see Issue #45). I want to make a windows task try app similar to the old Oculus service manager that let you start/stop PSMoveService and view the event log. You can actually install PSMoveService.exe as a proper windows service by launching it with the "-i" option, but I don't have anyone do that right now because there is currently no good way to get the service log data if you launch it that way right now. I actually have a stub for the windows task try app written, but I still haven't checked it in yet.

Since I already have an issue tracking this request I'm going to close this issue, but feel free to continue commenting in issue #45 if you have additional requests about this feature.
