### ISSUE TITLE
PS move light not working

### ISSUE THREAD

**Issue by HaxOR359** [cboulay/PSMoveService#138]
So I've used the program with one controller to test it out and I decided to add a second controller but that's when problems started happening. Long story short the second controller light isn't working but the first controller light is working. Is there any fix for this?
![move not working](https://cloud.githubusercontent.com/assets/20671583/17158513/c93b0042-5364-11e6-8e17-86328834ea1c.png)
![not working](https://cloud.githubusercontent.com/assets/20671583/17158511/c936f592-5364-11e6-9f9b-e3554cf32b72.PNG)
![working](https://cloud.githubusercontent.com/assets/20671583/17158512/c93a3ad6-5364-11e6-9a51-28c3bdc3031c.PNG)

**Comment by cboulay** [comment]
Does it turn on under any circumstance? test rumble, etc?
What if you restart the PC (sadly, the fastest way to disconnect the controllers without screwing up the pairing) then turn them on in different order? Is it still the second-on one that won't light up? I'm just trying to rule out a hardware problem here.

**Comment by HaxOR359** [comment]
With some testing, I found out that it only lights up once steam VR is running. I haven't tried restarting my PC to see if it happens but my guess is that it might not change anything.

**Comment by pearce31** [comment]
Only one controller is used and lights up in the configuration tool.

**Comment by HipsterSloth** [comment]
> With some testing, I found out that it only lights up once steam VR is running

By default the controllers won't light up unless a connected client tells them to. When you launch SteamVR the psmove plugin connects to PSMoveService, gets a list of all connected controllers, and turns on their lights. 

The config tool also connects to PSMoveService, but won't turn on the controller light unless the specific config stage needs it for some specific use case. Most of the config tools only use the first controller (color calibration, tracker pose estimation, etc). If you want to test the light on a particular controller, the best way is to select the controller in the controller settings, and do the rumble test. When you pull the trigger in the rumble test it will also light up the controller based on the rumble amount.

Once the psmove plugin is registered with SteamVR you will see the controllers light up when you launch the config tool, but that's only because the config tool connected to SteamVR (to get the HMD position) which causes steamVR to launch, which causes steamVR to connect to psmove service as a client.
