### ISSUE TITLE
i lose control when i turn back

### ISSUE THREAD

**Issue by vrxiaochouyu** [cboulay/PSMoveService#140]
i think the reason is the PSEye can‘t see the controller when my body from the controller ,so that i lose control when i turn back.
i see @cboulay set two PSEyes Shoulder to shoulder. And i found two PSEyes must see the controller at the same time,otherwise it will lost control.
can i set two PSEyes face to face？i found the distance of the controller is different between front and rear 

@hawkinse if i set two PSEyes face to face, the HMD will can't move in steamvr. when i use freePIE bridge.
another question is the virtual controller for HMD is also display in steamVR.

**Comment by hawkinse** [comment]
@vrxiaochouyu I use three cameras, while I tried two in the past I didn't use them face to face. I'd think you would still get some movement though, even if it doesn't track very well or have very good range. Is yellow calibrated properly in PSMoveConfigTool? Are you sure the cameras are angled in a way that they can see the bulb at head height?

With regards to the tracking controller being visible in Steam VR, that's not something I can fix on my end. All PSMoveService clients are capable of seeing all controllers, so the SteamVR plugin will show three controllers. If you don't mind building PSMoveService from source, it is possible to limit the SteamVR plugin to only seeing two controllers by editing the for loop in the HandleControllerListResponse of driver_psmoveservice.cpp. Change it from

`for (int list_index = 0; list_index < controller_list->count; ++list_index)`
to
`for (int list_index = 0; list_index < (controller_list->count > 2 ? 2 : controller_list->count); ++list_index)`

This also makes some games which get confused by extra controllers playable when using a third for head tracking (ex. Skeet: VR Target Shooting). It would be nice if limiting the number of controllers available to the Steam VR plugin were a setting so that other controllers could be used by other utilities at the same time, but as far as I know all the settings in PSMoveConfigTool are for the service itself and the Steam VR plugin isn't set up for user settings outside of what Valve offers.

**Comment by HipsterSloth** [comment]
> It would be nice if limiting the number of controllers available to the Steam VR plugin were a setting so that other controllers could be used by other utilities at the same time

It's actually possible to add plugin specific setting to steamvr.vrsettings. I already have some custom settings for psmove button mappings. It'd be pretty straight forward to add a controller limit option for the plugin. I can add that for next release.

**Comment by vrxiaochouyu** [comment]
@hawkinse i have tried your new version in 7-27. it‘s solved. thank you！
just need psmovesever change the controller being visible. wait for the next  psmovesever version.

**Comment by luizlago** [comment]
> All PSMoveService clients are capable of seeing all controllers, so the SteamVR plugin will show three controllers. If you don't mind building PSMoveService from source, it is possible to limit the SteamVR plugin to only seeing two controllers by editing the for loop in the HandleControllerListResponse method of driver_psmoveservice.cpp. Change it from
``` for (int list_index = 0; list_index < controller_list->count; ++list_index) ```
to
``` for (int list_index = 0; list_index < (controller_list->count > 2 ? 2 : controller_list->count); ++list_index) ``` 

@hawkinse I tried build with this change...but didn't change. My SteamVR still show 3 controllers.

**Comment by vrgamer** [comment]
hi
I have connected 3 pseyes at different usb ports, color calibration is ok and pose calibration is also ok showing
Traker 1 complete
Traker 2 complete
Traker 3 complete
But when i get into steam vr only one camera is tracking the psmoves, so when i turn back it stops tracking the psmoves. How can I get 360º.
Any help would be appreciated

**Comment by masterchop** [comment]
My expireance:
  I was working with 2 cams and 3 controllers very good tracking but only 180 degress.
  Get 3 more cameras but connect 2 so I end up with 4 trackers. (3 USB Controllers)

  When i plugged the new cams everything failed, even i unplug them. i leave old setup. So i had to redo the entire setup again, i mean controllers alone no HMD and them with HMD for all controllers and all cameras. after that i got success.

  In your scenario make sure you dont have any other app using the cams feed. 
  Dont open the PSconfig tool and open SteamVR before that. I have notice that sometimes becuase i have both open 1 shows very good tracking but the other is all messup, so i just close everything and re-open, and it fixes by its own.

**Comment by HipsterSloth** [comment]
When you do the pose calibration it is computing the camera poses for all ps3eye's at once. The thing you have to do per ps3eye is the color filter calibration (since every camera has slightly different light environment). The most common problem I've seen is that one camera has the color calibrated correctly, but the other cameras do not.

That said, because you are seeing:
> Traker 1 complete
Traker 2 complete
Traker 3 complete

This implies to me that you are getting tracking samples for each camera. Do you have a window or other reflective surfaces in view of any of your cameras? I've sometimes seen cases where sunlight on the carpet will create a bright blob that get's confused for the PSMove controller. You can see if this is the case when looking at the video feed with the HSV filter mode on and see if there are any blobs showing up that aren't the controller.

When you are running the pose calibration can you see the controller getting the white outline around the controller in each video feed? 

Example here in lower left hand corner of this video:
https://www.youtube.com/watch?v=XiLYa1EZL04&t=6m36s

**Comment by vrgamer** [comment]
I dont have any reflective surface. I can see the outline around magenta move when doing pose calibration. I have removed a camera and tried with 2 cameras but I still have tracking with one of them. 
Thank you very much

**Comment by vrgamer** [comment]
Solved !!! Of course I had only 1 camera confired correctly in UsbDeview

**Comment by HipsterSloth** [comment]
Closing old support issues. If this is still a problem please post a request to the google group:

https://groups.google.com/forum/#!forum/psmoveservice
