### ISSUE TITLE
Switch the color of control2

### ISSUE THREAD

**Issue by douglassimoes** [cboulay/PSMoveService#143]
Today I finally could calibrate thanks to the help of developers and contributors, but unfortunatelly my pseye thinks that cyan and magenta are the same color, so I managed to work and tested with cyan and yellow and everything worked fine, until I open some game and the control2 color switched back to magenta. So there is a way to change the default color of control2? I would appreciate if anyone could write here your color configuration for magenta and cyan.

**Comment by douglassimoes** [comment]
I managed to work the problem was that my gain and exposure values were too low, I switched the both variables to 56 and everything worked.

**Comment by HipsterSloth** [comment]
Glad to hear that gain and exposure settings fixed it for you. We probably should add suport at some point for allowing the user to define tracking color order since some colors can be harder to track in certain lighting conditions. We can probably do that work at the same time we add support for auto-color calibration.

**Comment by zelmon64** [comment]
An easy hack to change the colour assignment is to turn the PSMove off and back on while PSMoveService is running because it will re-connect as a different controller.
