### ISSUE TITLE
Only one PSMOVE recognized

### ISSUE THREAD

**Issue by HyppoNymous** [cboulay/PSMoveService#153]
Using PSMove config tool and the "controller settings " i can change the PSMove ID to test orientation and calibrate the first PSmove with ID = 0 and the second PSmove with ID=1
When i use "Tracker settings" to "Compute tracker poses" it only works with the first PSmove with ID = 0 by default,  there is no way to change the PSmove ID = 1  to "Compute tracker Poses" with the second PSmove.
SteamVR recognizes two controllers, but in game or in Compositor mode i always see one PSmove controller, it is related to previous issue ? 
SteamVR says for the second PSmove it is recognized , but it's position is not detected.

**Comment by Gary00** [comment]
Seems like I was having the same issue.

**Comment by HipsterSloth** [comment]
The "compute tracker poses" tool only uses the first controller. It just needs a lit controller to figure out where the cameras are relative to the calibration mat. Nothing is saved for that particular controller. My guess is that you need to configure the cyan tracking color in the color configuration tool for each tracker. Sounds like magenta is calibrated fine since it's showing up in steamvr.

**Comment by HyppoNymous** [comment]
How can i configure cyan tracking color for each controller ? Psmove config tool seems not having some option to change the color for each PSmove controller.
When i launch SteamVR , color attribution is automatic, i have one Magenta and one Cyan. It is something to change in SteamVR settings files on SteamVR installation folder ?
