### ISSUE TITLE
SteamVR PS move controllers blinking

### ISSUE THREAD

**Issue by HyppoNymous** [cboulay/PSMoveService#154]
The PSmove controlers are blinking in Steam VR or games like The Lab and WindLands.
Launching test_openGL.exe from psmove_unity5_master/Assets/plugins, the controllers capture is fast and smooth.
Is blinking related to some slow data transfert rate between PSMove Service and Steam VR ? Or some multi threading issue ?

**Comment by zelmon64** [comment]
@HyppoNymous This sounds like the flickering noted in #136. It has since been fixed and there is an unofficial build in that issue if you'd like to try it.

**Comment by HyppoNymous** [comment]
Your build works better , there is no blinking anymore,thank you.
It seems like some latency between PSmove controllers movement and SteamVR in game , perhaps i would need a more powerfull PC ? 
Because launching test_openGL.exe (from psmove_unity5_master/Assets/plugins), the controllers capture was pretty fast and fluid.

**Comment by HipsterSloth** [comment]
@HyppoNymous psmove_move_unity5 uses psmoveapi, which embeds the all the camera and controller processing directly into your application. In contrast, PSMoveService is a separate app that networks controller data to a client over UDP. There are some things we can do to improve this. The first will be to get the Kalman filter working. This will allow us to pass less noisy controller physics to steamvr which will let us do pose prediction to compensate for latency. I'm going to start working on this next week. The other option is to support streaming controller data over an interprocess communication mechanism like a named pipe, rather than a socket like we are now, but that feature is further out. We started with a socket because that was the most flexible (let's the client be on another machine).

**Comment by zelmon64** [comment]
@HyppoNymous I'm wondering if this lag is similar to #117. The fix was to reinstall Windows but the issue was more in the calibration tool than SteamVR. How does the performance in the calibration tool compare? There are a few theories in that issue.

**Comment by HipsterSloth** [comment]
@zelmon64 that's a great point. I forgot about that issue. My theory there is that something is causing the udp stream to get severly buffered, but I never figured out what could be causing that (I could never repro the issue).

**Comment by HyppoNymous** [comment]
@zelmon64 
I have no lag when i use the calibration tool, the camera capture is smooth and real time.
When i use "test tracker video feed", i notice a very light lag , instead of beeing 1:1 capture it looks more like 1:0.7 , it is not smooth as psmove_move_unity5 

@HipsterSloth 
+1 for Kalman filter

**Comment by HipsterSloth** [comment]
Updating bug title to reflect lag issue (since the flicking issue is fixed).

**Comment by HipsterSloth** [comment]
Fixed in latest release: https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha4.6
