### ISSUE TITLE
idea recenter button

### ISSUE THREAD

**Issue by HyppoNymous** [cboulay/PSMoveService#159]
When calibration is done if i change the camera orientation or height i don't want to do the calibration again, i would like a quick button on the calibration tool to tell "this is the new height and center point" putting my PS move in front of my helmet for example.

**Comment by HipsterSloth** [comment]
I'm actually working on this right now. I plan to get this in for the next release I want to put out on Sunday.

**Comment by HyppoNymous** [comment]
Awesome :)

**Comment by Bungpiece** [comment]
Glad to hear the turn around on this issue from  #59 
@HyppoNymous  if you have a kinect at hand you can also try this OSVR plugin for positional tracking albeit at 30hz.
https://github.com/simlrh/OSVR-fusion

**Comment by HipsterSloth** [comment]
Scratch that. I took a stab at getting it to work, but it turns out that it's not immediately apparent how to the HMD pose from inside the psmove steamvr driver plugin (you can only get the poses of the devices your plugin provides). Getting the HMD pose will take a bit more work, which I'm going to do on Monday. In the meantime, there is a new release: https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha4.6
