### ISSUE TITLE
Pairing/Unpairing not reflected until service restart

### ISSUE THREAD

**Issue by cboulay** [cboulay/PSMoveService#16]
Using OS X.

Using the PSMoveConfigTool to pair a controller. The controller list is still empty after successful pairing. If the PSMoveService is then stopped and restarted, the previously paired controller now shows up in the list.

The same behaviour occurs for unpairing; the controller still appears as paired until the service is restarted.

**Comment by cboulay** [comment]
A couple more issues in the controller paring GUI.

On Windows, after completing 6/6, the only button available was 'cancel'. It still worked, but this was confusing and I was worried canceling would have undone the pairing.

In OSX, the permissions window popped up while on step 4/6, covering the text (the window is movable). After entering my password, the app exited out of the pairing window while still on 4/6. I did not yet press the PS button. Pairing was already complete at this stage evidenced by the fact I could connect by pressing the PS button when out of the pairing app and the controller showed up in my BT device manager.

**Comment by HipsterSloth** [comment]
There were a ton of bugs here but the biggest issue was actually due to a bug handling messages from the server sent back to back. If there were multiple messages in the same frame each event would point to the last set of message parameters received that frame, rather than their own. SO if you have messages A, B, and C received in one frame when you processed all three messages you would just get the parameters for C 3 times in a row.

It also turns out that the bluetooth request code would sometimes stall the main thread long enough to cause it not keep up with reading the video frames the ps3eye camera thread was pumping out. There video frame write thread wouldn't signal the reader thread when the video frame queue was full and the main thread was stuck waiting for notification of new frames. The resulting deadlock would cause the service to never report completion back to client. 

I also cleaned up a ton of stuff with how usb connected controllers are handled and dealt with in the client UI. 

All of this work made it back up to the master branch with change ce1e245e6ff097ad12c36b6c01c82528bd68e7e2
