### ISSUE TITLE
Cant get to the next level in nVidia fun house game

### ISSUE THREAD

**Issue by booty156** [cboulay/PSMoveService#167]
How do I go onto the next level in nVidia FunHouse?

**Comment by HipsterSloth** [comment]
The issues page is not the place for questions about games. If you have a question about a specific issue with the PSMoveService then please post the details about that. We already have enough issues to deal with. Please don't needlessly flood the issues page.

**Comment by HipsterSloth** [comment]
Sorry that may have been a bit harsh as we could have been more clear about what is and is not an appropriate issue to post. I just added the following to the front of the project page:

"If you are having trouble with a game while trying to use PSMoveService, please be clear about how the problem you are having with the game relates to PSMoveService. For example, saying "I can't throw the ball in X because there appears to be no physics" is a good bug. Saying "I can't get through this game" doesn't help us debug it. Chances are that we don't have the game you are trying to play and have no context for how it's suppose to work. Our time is also stretched thin just trying to get this service working in the first place so please help us by trying to debug the issue as much as you can yourself and posting your findings. Also understand that making a particular game work for you is a low priority for us until we finish getting some major features in place."

If you can explain how PSMoveService is preventing you from advancing in the game, please feel free to re-open this issue with the updated description. Just please understand we have a lot of issues to work through and we need people to help us debug this issue. Help us help you by being specific about your problem and understand that we have a small amount of time to troubleshoot these problems.
