### ISSUE TITLE
Position Tracking with FreePieBridge not working anymore

### ISSUE THREAD

**Issue by luizlago** [cboulay/PSMoveService#168]
Hello! After pull new commits (latest: 4cef4b1) and rebuild...I tried using [PSMoveFreepieBridge](https://bitbucket.org/hawkinse/psmovefreepiebridge) as before...but Positional Tracking not worked, nothing happened. Any idea?

**Comment by HipsterSloth** [comment]
Ah crap. I had to change the client interface for the support the new DualShock4 controller support I'm working on. This almost certainly broke the PSMoveFreepieBridge (which I don't maintain). The latest binary release (alpha4.6) should still work, but anything past commit 830cd18017ad3d47b62b42460915c895d562bc0f will likely stop working until PSMoveFreePieBridge is updated. 

@hawkinse Sorry I probably should have dropped you a line about these changes coming down the pipe. It should be pretty easy to adapt the the freepie bridge to the new client interface changes. I believe the psmove specific stuff is mostly the same. Most of the new code has to do with the addition of new dual shock 4 related controller structures and some modified enums.

**Comment by hawkinse** [comment]
@HipsterSloth @luizlago No worries, I expected things like this would occasionally happen since the client interface isn't finished. I'll be able to work on getting that fixed tomorrow.

**Comment by HipsterSloth** [comment]
Thanks @hawkinse! I'll try to keep you in the loop the next time we update the client interface, which I think will be when we flip the switch over to the C-API were working on.

**Comment by hawkinse** [comment]
I suspect the breakage occurred because the values of a few constants have changed. I can still build PSMoveFreepieBridge with no code changes with the updated PSMoveClient header files. I'm still building PSMoveService, so I'm not sure if that's all I needed to get things working again.

I ran into an issue updating my PSMoveService source. Pulling via git conflicted with some of my local changes (not surprised), and attempting to clone a clean copy failed failed on protobuf:

`fatal: destination path 'thirdparty/protobuf' already exists and is not an empty directory.`

`Clone of 'https://github.com/google/protobuf.git' into submodule path 'thirdparty/protobuf' failed`

It might be that I was just doing something stupid, and I was able to work around it by deleting the protobuf directory mid-checkout before it started to clone it. I'll make another post once I'm done building PSMoveService and have verified that the updated headers fixed the issue.

**Comment by HipsterSloth** [comment]
Yeah I believe we updated the protobuf submodule link. Updated submodules can be a real pain when updating a pre-existing clone. My git-fu is weak so I don't know what the "right" way to do that is (@cboulay might know), but I usually do what you did and just delete the submodule folder (sometimes I just do a fresh pull of everything). I think we actually want to switch over to using cmake's external_project mechanism and drop submodules altogether at some point so this sort of thing won't be an issue anymore. 

Thanks for the update!

**Comment by cboulay** [comment]
@hawkinse 
After doing the usual `git fetch` and `git pull`, you have to follow that up with a `git submodule update`. That should be all that is needed.

However, sometimes the build process will add some things to the submodule, and those things aren't properly ignored by the submodule's .gitignore file, so the submodule will be in a dirty state. When that happens, I usually change into the submodule directory (so now git commands apply to the submodule's repository) and do a `git clean -f`. Then `cd ..` out of there and try `git submodule update` again.

**Comment by hawkinse** [comment]
@luizlago is PSMoveService able to access your cameras? In my log for PSMoveService I'm seeing the messages like:

`libusb: error [winusbx_claim_interface] could not access interface 0: [87] The parameter is incorrect.

[2016-08-10 11:55:06.765]: PS3EyeTracker::open - Failed to open PS3EyeTracker(USB\VID_1415&PID_2000\3\1, camera_index=1)`

and in the tracker settings in PSMoveConfigTool I'm only seeing the message "No trackers controllers" instead of options to calibrate or test tracking. If PSMoveService can't use the cameras, PSMoveFreepieBridge can't track the controllers.

@HipsterSloth a copy of my log can be found [here](http://pastebin.com/gZCzVvEN) if it helps.

**Comment by HipsterSloth** [comment]
You aren't running the Win10 anniversary update by chance are you? There was a change they made that prevents devices from being opened in exclusive mode (http://windowsreport.com/anniversary-update-exclusive-mode-game-controllers/). 

> As of update 1607, kernel32.dll CreateFile() using only the flags GENERIC_READ and GENERIC_WRITE and 0 for dwShareMode no longer allow exclusive (non shared) access to devices needed in some circumstances.
An example of a device that is not allowing exclusive access any more is the Sony Dualshock 4 Game controller.

I'd need to dig into libusb and see if in fact it's trying to open the camera this way.

**Comment by HipsterSloth** [comment]
Also this is me grasping at straws but have you tried re-installing the libusb driver for the camera? Also does test_camera.exe work for you or does it fail the same way?

**Comment by hawkinse** [comment]
@HipsterSloth yep, I am. However, previous versions of PSMoveService work fine. At least, alpha 4.5 does. Haven't tried 4.6.

test_camera fails with the same output. I have not yet tried reinstalling the libusb driver.

**Comment by HipsterSloth** [comment]
@hawkinse Looks like this isn't a new issue (can't blame Win10AU). I forgot about this same problem was posted a while ago: https://github.com/cboulay/PSMoveService/issues/56

I'm hoping some combination of reinstalling the drivers or changing USB ports will fix the issue for you.

**Comment by cboulay** [comment]
>that prevents devices from being opened in exclusive mode

That reminded me of what happened with hidapi and Windows >= 8. [Here](https://github.com/signal11/hidapi/commit/b5b2e1779b6cd2edda3066bbbf0921a2d6b1c3c0) was the commit that fixed it. I don't know if this applies to libusb but it might be relevant.

**Comment by hawkinse** [comment]
@HipsterSloth thanks for posting that issue! Reinstalling alone didn't help, but switching from libusb-win32 to libusbK fixed it.

@luizlago [try this version of PSMoveFreepieBridge](https://mega.nz/#!XR1QXDqR!b7SR8ILZ-847pLa5nrhlE-c7DaN1-GtbO0rNeu05yIs). I don't want to post it to my downloads page yet since it doesn't work with current releases of PSMoveService. Included is a release and a debug version, use the same version as the one you compiled PSMoveService as.

**Comment by zelmon64** [comment]
@hawkinse if you now switch back to libusb-win32 does it work? This trick of having once used libusbK then using libusb-win32 used to be a big issue. It used to be that you'd have to switch back to libusb-win32 after a reboot because libusbK would then not work.

**Comment by hawkinse** [comment]
@zelmon64 yep, switching back to libusb-win32 works. Good catch!

**Comment by zelmon64** [comment]
@hawkinse that's very interesting that this issue has re-emerged. It's particularly annoying because as I said, libusbK will stop working after you reboot your computer. It is also particularly strange because you now never have to reinstall libusbK unless you restore your computer to a time before libusbK was installed. You can even uninstall all drivers for the PSEye then reinstall libusb-win32 and it will be fine. Obviously something gets permanently altered but I can't see why it should.

This oddity was quite the thorn in my side when working with the FreePIE PSMove plugins which is why I'm particularly vocal about it!

**Comment by HipsterSloth** [comment]
@zelmon64 The windows implementation of libusb has been a continuous source of grief for me as well since the start of this project (OS X hasn't really been an issue). Down the road I want to look into making a proper camera driver for Windows using the WinUSB api. The amount of hoops we have to make users jump through to keep a camera working is unfortunate. When I do work on the PS4 Camera it will probably force the issue of making a platform specific driver because there is no high speed isosochronous transfer support in the windows implementation of libusb (you have to patch it in).

**Comment by luizlago** [comment]
> @luizlago is PSMoveService able to access your cameras? In my log for PSMoveService I'm seeing messages like:
libusb: error [winusbx_claim_interface] could not access interface 0: [87] The parameter is incorrect.
[2016-08-10 11:55:06.765]: PS3EyeTracker::open - Failed to open PS3EyeTracker(USB\VID_1415&PID_2000\3\1, camera_index=1)
and in the tracker settings in PSMoveConfigTool I'm only seeing the message "No trackers controllers" instead of options to calibrate or test tracking. If PSMoveService can't use the cameras, PSMoveFreepieBridge can't track the controllers. 

Yes, is show up for me too. My log: 

`[2016-08-10 21:04:21.129]: PS3EyeTracker::open - Opening PS3EyeTracker(USB\VID_1415&PID_2000\0\0, camera_index=0)libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
ps3eye::PS3EYECam::getDevices() found 2 devices.`

But, apparently my 2 pseyes working in test_camera and configtool too.


> @luizlago try this version of PSMoveFreepieBridge. I don't want to post it to my downloads page yet since it doesn't work with current releases of PSMoveService. Included is a release and a debug version, use the same version as the one you compiled PSMoveService as.

I going test now! Thanks!

**Comment by luizlago** [comment]
@hawkinse
> @luizlago try this version of PSMoveFreepieBridge. I don't want to post it to my downloads page yet since it doesn't work with current releases of PSMoveService. Included is a release and a debug version, use the same version as the one you compiled PSMoveService as.

work fine! Thanks!!

**Comment by HipsterSloth** [comment]
@hawkinse I finally just published a [release](https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha5.0) with the DS4 changes. Let me know when you have posted the new version of PSMoveFreepieBridge and I'll update the release notes. If anything comes up please feel free to start a discussion on the newly opened forum: https://groups.google.com/forum/#!forum/psmoveservice

**Comment by HipsterSloth** [comment]
Actually I should leave this issue open until the new PSMoveFreepieBridge build is up

**Comment by hawkinse** [comment]
@HipsterSloth Updated version is up.

**Comment by HipsterSloth** [comment]
@hawkinse Thanks for the quick turn around! I updated the release notes with a link to the latest version of PSMoveFreePieBridge.
