### ISSUE TITLE
Processing library

### ISSUE THREAD

**Issue by Octav1an** [cboulay/PSMoveService#174]
Hello everyone, for the last couple of days I've been trying to build a working library for processing with not much luck. I try many psmoveapi repos, only the one by thomas worked without any errors, your version is giving me

 `[  1%] Building C object CMakeFiles/psmoveapi_static.dir/external/hidapi/windows/hid.c.obj
[  3%] Building C object CMakeFiles/psmoveapi_static.dir/src/psmove.c.obj
In file included from C:/Users/Octavian/Desktop/newOne/include/psmove.h:44:0,
                 from C:\Users\Octavian\Desktop\newOne\src\psmove.c:31:
C:/Users/Octavian/Desktop/newOne/include/psmove_time.h:61:23: error: unknown type name '__int64_t'
 ADDCALL psmove_usleep(__int64_t usec);
                       ^
CMakeFiles\psmoveapi_static.dir\build.make:87: recipe for target 'CMakeFiles/psmoveapi_static.dir/src/psmove.c.obj' failed
mingw32-make[2]: *** [CMakeFiles/psmoveapi_static.dir/src/psmove.c.obj] Error 1
CMakeFiles\Makefile2:140: recipe for target 'CMakeFiles/psmoveapi_static.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/psmoveapi_static.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
mingw32-make: *** [all] Error 2
` 

error. Anyway when I run any processing sketch I am getting an error `PSMOVE CRITICAL] Assertion fail in psmove_poll: move != NULL` the controller is paired and connected with my laptop which runs Windows 8.1. The PSMoveService works fine, calibration and orientation test are working. I've seen you started a issue about difficulties on windows 8 & 8.1 but it didn't get me anyway. Does somebody knows or have a working library for Processing on Windows 8.1? Thank you.

**Comment by HipsterSloth** [comment]
It looks like you are trying to use psmoveapi with psmoveservice? That definately won't work. They are two completely independent implentations (though we adapted some of the bluetooth and psmove hardware code from psmoveapi) . If you want to make a processing wrapper for psmoveservice you have two options. We have a "client_capi" branch that wraps the client c++ api for psmoveservice in C. This makes it easier to make wrappers for other languages. @cboulay used this to make a python wrapper. The long term plan is to replace the c++ client interface with the c one, but that has to happen after we finish some other features. The other option is to use the existing C++ client interface. @hawkinse did this for his FreePIE bridge (C++ to C#). I don't know how hard it is to wrap c++ functions for processing. Finally you could just skip psmoveservice altogether and stick with thp's psmoveapi. If you do that, don't run psmoveservice since it will interfere with psmoveapi trying to access the controller directly. This route is probably the easiest route for you at this point (depending on your needs).

**Comment by HipsterSloth** [comment]
For reference in case you are curious:

The capi branch I was referring to: 
https://github.com/cboulay/PSMoveService/tree/client_capi

The C++ client API: https://github.com/cboulay/PSMoveService/blob/client_capi/src/psmoveclient/ClientPSMoveAPI.h

The C client API:
https://github.com/cboulay/PSMoveService/blob/client_capi/src/psmoveclient/PSMoveClient_CAPI.h

Test client written using the C++ api:
https://github.com/cboulay/PSMoveService/blob/client_capi/src/tests/test_console_client.cpp

Test Client written using the C api:
https://github.com/cboulay/PSMoveService/blob/client_capi/src/tests/test_console_CAPI.cpp

cboulay's python wrapper and test cases:
https://github.com/cboulay/PSMoveService/tree/client_capi/misc/python_capi

hawkinse's freepie wrapper using the C++ client interface:
https://bitbucket.org/hawkinse/psmovefreepiebridge

**Comment by HipsterSloth** [comment]
For what it's worth, the C-API is now the official client interface (The C++ client interface is now gone). This should make it a lot easier to make a binding for processing. Closing this issue for now, but feel free to re-open if you are still working on this and have an issue making a processing binding work.
