### ISSUE TITLE
Calibrate Tracking Colors only 1 controller lights up

### ISSUE THREAD

**Issue by bbopper** [cboulay/PSMoveService#175]
I have followed all the steps up to this point with no issues.  Both cameras and both controllers work (both pass orientation & rumble) .  When I press Calibrate Tracking Colors only controller 0 lights up.  I'm running windows 10 and this happens on both 4.5 and 4.6.  Thanks in advance for any help on this.

**Comment by ozzeruk** [comment]
You only use 1 controller for this step.

Put the 2nd controller in a different room (that's what I do anyway!)

Put the first controller in the centre of your space, then what you do is scroll through the colours, calibrating each one, as you do that the colour on controller 0 changes.

Once you have finished each colour for each tracker, then fetch your second controller back and continue.

I do this and my system works fine.

**Comment by HipsterSloth** [comment]
Yeah like ozzeruk said, only the first controller is used to calibrate colors. The assumption being that if a tracking color calibration is good for one psmove on a given camera, it's good for another psmove. 

That assumption actually doesn't hold true anymore for the dual shock 4. In the next release you'll be able to adjust the color filter per controller per camera. That feature is already checked in to master, but I haven't made a new release yet because there is a crash issue with the new gyro calibration tool I haven't tracked down yet.
