### ISSUE TITLE
Framerate of cameras significantly reduced when rift begins tracking

### ISSUE THREAD

**Issue by elienassif** [cboulay/PSMoveService#180]
When my headset (oculus cv1) is not tracking, the tracking of the ps move controllers is fluent and accurate. However when the rift begins to track, the framerate of the cameras is significantly reduced to something like 10 fps, where its so unnatural to even hold the controllers. I dont think my pc is creating any bottlenecks as its relatively high performance. Does anyone have any suggestions? Oh and I assume its not usb bandwidth because they work fine when the headset isnt tracking and they are not connected into hubs. Any solutions? Thanks.

**Comment by HipsterSloth** [comment]
I wouldn't rule out a potential USB bandwidth issue just yet. 

If you run test_camera.exe (without psmoveservice running) do you get a drop in the video feed frame rate when oculus tracking starts? If so that is a tell tale sign of USB bandwidth issues.

The Oculus "sensor" is an HD USB camera that turns on when the Oculus headset starts tracking. This eats up a non trivial portion of the bandwidth available to a given usb root hub. Multiple USB ports can share the same root hub (even the ones on the back of your mobo). The problem is trying to determine which ports share the same root hub.

In the "Windows Developer Kit" you can find a nice utility called USBView that shows a tree of all USB devices and which root hub you are plugged into. I have just the EXE zipped up here:

[usbview.zip](https://github.com/cboulay/PSMoveService/files/415991/usbview.zip)

You might launch that and see which cameras are plugged into which root hubs. Here is what mine looks like (two cameras):

![image](https://cloud.githubusercontent.com/assets/16793853/17633483/5cf2c80e-6082-11e6-93ab-7e58178ce5b0.png)

If the oculus camera is connected to the same root hub as the psmove cameras I would try and moving the oculus camera to a different USB port and try again.

Sadly I don't have any good recommendations for measuring USB bandwidth consumption in a user friendly way.

**Comment by elienassif** [comment]
Thank you so much for the quick reply, I'll give it a try when I'm home and
I really hope it works. Thanks again man!

**Comment by cboulay** [comment]
@elienassif Any update? I'm doing some housekeeping and would like to close the issue.
