### ISSUE TITLE
Throwing items in games

### ISSUE THREAD

**Issue by gladiusz** [cboulay/PSMoveService#183]
Hi. Is it possible to throw items in games? For example it doesn't work in The Lab or in Budget's Cuts. Are there any plans to make it works?

**Comment by HipsterSloth** [comment]
This is the same issue as #133. We don't currently provide a velocity or acceleration from PSMoveService to SteamVR, resulting in the inability to throw things. The original implementation of velocity estimation came from taking the derivative of the smoothed optical position, but this was too noisy and resulted in bad controller jitter in steamvr, so I took it out. We are currently working on a Kalman filter that will provide this state with less noise. I'm actually debugging this now, though I make no promises on when it will be ready. 

Because this is technically a dupe, I'm going to close this issue for tracking purposes, but feel free to continue discussion here.
