### ISSUE TITLE
Forums for the PS Move Service

### ISSUE THREAD

**Issue by CircuitLord** [cboulay/PSMoveService#194]
I've noticed that the issue section here is a little overloaded with questions, asks for help, and ideas. I thought it would be a good idea to make a forums to do all of this on. Thus, I created (we have decided not to use this)

If any of the admins here dislike this in any way, I can remove it. But if not, I think it would be very helpful to this project. I would be glad to make the admins here admins on the forums, or give them complete control if they wanted.

Let me know what you think, again, I will remove this if wanted.

**Comment by HipsterSloth** [comment]
I can't speak for @cboulay, but I'm totally down for this. I too feel like the issues page is getting overloaded with support requests, when it's really best suited for tracking actual bugs. Not that I fault anyone for using the issues page for support requests. It was the only option we had. I've seen gitter used for this sort of thing before, but I'm not married to any particular forum implementation. I've also wanted a place to post announcements and updates about what we're working on and it's kind of awkward to do that on GitHub at present (editing the Readme for this seems a bit silly).

**Comment by CircuitLord** [comment]
Thanks!

**Comment by CircuitLord** [comment]
If you want to make an account on there, I can make you an admin. I also added a Updates & Announcements section where only admins can post.

**Comment by cboulay** [comment]
Are there any stack exchanges this could fall under?
gamedev is close but not quite. Maybe because the vast majority of questions are about SteamVR integration we could use [gaming](http://gaming.stackexchange.com/).

We could also use a google group.

I'm not against a forum, but I want something discoverable (well-indexed), and zero maintenance. If we go with a forum then there can only be one subforum / category that users are allowed to post to. That + "Updates & Announcements" is all that is needed. From experience I know that, try as we might, we can never get people to post in the right category. The other problem with software-support forums I've administered in the past is spam, making the forums essentially unusable. How is forumotion for that?

Anyway, I'm not sure we need to do that just yet. I think we can do a couple things to help decrease the number of open issues and people posting support questions. First of all, we write in the wiki and the readme something along the lines of "You must begin your issue text with a statement that you've read the wiki and searched the issues. Failure to include this statement will result in your issue being deleted immediately." Second, we don't directly answer people in the issues, rather we edit the Wiki and send them there. Or, we could have a conversation in the issues page but when we figure it out we make sure to put something about it in the Wiki.

The other thing we should do is aggregate all the issues that are about poor co-registration and put them into a single issue. Aggregate all the issues that are about RiftCat and put them into a single issue.

I tend to be a bit heavy-handed with stuff like this, so I haven't been doing it so far. @HipsterSloth has been way nicer than I could possibly be so I've deferred to his judgment on how to handle it. I also don't know the answers to most of the questions because they're almost all about things that go wrong when trying to play games and that's all HipsterSloth's domain... I'm just an academic.

I can probably find a few hours this week to go through the issues and clobber most of them, trying to create Wiki entries where I'm able.

**Comment by CircuitLord** [comment]
Okay, I can change the forums to have just 2 sections "Discussion and Updates & Announcements" if you guys think that is necessary. 

I can handle most of the forum maintenance if you want. I do think that the PS Move Service needs a place for people to just chat about it, I'm not sure what the best way to do that is though. 

I personally think the method you suggested would get very complicated overtime, but you can do it for now until you guys decide what you want to do.

**Comment by cboulay** [comment]
@CircuitLord It's only complicated if you're nice about it. However, if you're like me, then you'll just say things like, "Sorry, not supporting that." and close the issue.

Anyway, any argument for forumotion over google groups? I'd prefer google groups but I can be convinced otherwise.

**Comment by CircuitLord** [comment]
@cboulay Lol.

Well, whatever you think is best. I'll let your developer team decide.

**Comment by cboulay** [comment]
@CircuitLord , add an e-mail address to your profile or send it to me privately, then I'll invite you to the google group and give you admin priveleges. You can take a look around to see if you like it or not.

**Comment by cboulay** [comment]
Or, just ask for an invitation...
https://groups.google.com/forum/#!forum/psmoveservice

**Comment by CircuitLord** [comment]
Okay, I requested an invite.

**Comment by CircuitLord** [comment]
@cboulay It looks pretty good. You don't have to admin me on there if you don't want to.

**Comment by cboulay** [comment]
@CircuitLord , oh no, you're not getting out of the responsibility now.

I played around with it a bit just now. It has the option to make a post as a discussion or as a question. Question posts can have answers marked as 'favorite', and those answers will sit at the top.

**Comment by CircuitLord** [comment]
@cboulay Ha ha! Okay.

Okay, that sounds good. That favorite feature sounds like it will be helpful.

**Comment by CircuitLord** [comment]
Should I put something on the forum I made about moving to the new forum? Or should I just leave it for now?

**Comment by cboulay** [comment]
Only one post, last I looked. I think you can just take it down. I'm sure @NeoToriyama will understand. We'll edit the Wiki and README, and start pointing inappropriate issue-posters there, as soon as @HipsterSloth is on the google group.

**Comment by CircuitLord** [comment]
Okay. I commented on there telling him. I'll take the forum down in a bit.

**Comment by CircuitLord** [comment]
Forum deleted.

**Comment by HipsterSloth** [comment]
I'm on the google group now. How does the following edit sound for the README (changes in bold):

Getting Help
Please start with the wiki. If you can't find help with your problem then please search through the issues (especially the closed ones) to see if your problem has been addressed already. If you still find no previous mention of your problem ~~then post a new issue~~ **then you have one of two options:**

**A) Join us in the the [PSMoveService Google Group](https://groups.google.com/forum/#!forum/psmoveservice) to ask your question. There are several people there who have experience debugging problems with the PSMoveService.
B) If your problem actually is a new bug and you have files to attach (logs, pictures, etc) then go ahead and create a new issue. That said, it's probably best to start with the Google Group first anyway since we can help add context before posting an issue.** 

~~If you are having trouble with a game while trying to use PSMoveService, please be clear about how the problem you are having with the game relates to PSMoveService. For example, saying "I can't throw the ball in X because there appears to be no physics" is a good bug. Saying "I can't get through this game" doesn't help us debug it. Chances are that we don't have the game you are trying to play and have no context for how it's suppose to work. Our time is also stretched thin just trying to get this service working in the first place so please help us by trying to debug the issue as much as you can yourself and posting your findings. Also understand that making a particular game work for you is a low priority for us until we finish getting some major features in place.~~

**Comment by cboulay** [comment]
Sounds good.

**Comment by HipsterSloth** [comment]
It is done. README and troubleshooting wiki have been updated with links. Thanks for setting up the forums!

**Comment by HipsterSloth** [comment]
I'm going to close this issue. If anyone has any objections, please feel free to re-open.
