### ISSUE TITLE
Fast PSMove tracking

### ISSUE THREAD

**Issue by HyppoNymous** [cboulay/PSMoveService#199]
In this video the guy demonstrates a robust algorithm to track the PSMove.
[https://www.youtube.com/watch?v=0J5LaWykiIU](https://www.youtube.com/watch?v=0J5LaWykiIU)

From it's comments 
> Processing time should be 0.5ms per controller, unless I can share some of the blob extraction work, in which case it would be 0.43ms per frame + 0.07ms per controller.

What do you think guys ?

**Comment by CircuitLord** [comment]
Looks really accurate. I can't really compare it to the PS Move Server though, since they have been working on it a lot, and most demo videos for it are using outdated versions.

**Comment by cboulay** [comment]
The optical tracking algorithm we use in PSMoveService is largely based on this and I was in contact with Oliver Kreylos when I was figuring out the details. If you feel as though the optical tracking provided by PSMoveService is worse than what you see in this video then it's not because of the optical tracking. A few alternative reasons come to mind...

1. He is using a different camera.
2. He has optimized his environment.
3. He may be using some heuristics that restrict the search space (e.g. region-of-interest).
    * We plan to do something like this after we get the sensor fusion worked out.
4. You're only seeing the 2D representation. You don't know how much depth jitter there is. From information he's posted elsewhere, the z-jitter is about the same as what we get.

In the future, please make posts like this in the [PSMoveService google group](ups.google.com/forum/#!forum/psmoveservice).
