### ISSUE TITLE
PSMoveService stop work

### ISSUE THREAD

**Issue by vrxiaochouyu** [cboulay/PSMoveService#201]
[ERROR] ClientNetworkManager::stop - Problem closing the socket: 应用程序没有调用 WSAStartup，或者 WSAStartup 失败。
[ERROR] handle_server_connection_close_failed - Error disconnecting from service: 应用程序没有调用 WSAStartup，或者 WSAStartup 失败。

**Comment by vrxiaochouyu** [comment]
PSMoveService always stop working for a few seconds. and sometimes error like this.

**Comment by CircuitLord** [comment]
Please follow the instructions described in the Readme file.

Getting Help

Please start with the wiki. If you can't find help with your problem then please search through the issues (especially the closed ones) to see if your problem has been addressed already. If you still find no previous mention of your problem then you have one of two options:

A) Join us in the the PSMoveService Google Group to ask your question. There are several people there who have experience debugging problems with the PSMoveService.

B) If your problem actually is a new bug and you have files to attach (logs, pictures, etc) then go ahead and create a new issue. That said, it's probably best to start with the Google Group first anyway since we can help add context before posting an issue.

**Comment by HipsterSloth** [comment]
I'm going through and close all issues that are troubleshooting support related for tracking purposes.
