### ISSUE TITLE
Problem with Magnetometer

### ISSUE THREAD

**Issue by siliciorock** [cboulay/PSMoveService#206]
Hi.

I have a issue with the magnetometer calibration.
Never reach the % of the force settings, or 100%.

Both controllers.

So, when i play in SteamVR, controllers spins and point in random direccion.

**Comment by brendanwalker** [comment]
Sorry I missed this issue earlier. I have heard a few reports of some controllers not reporting a usable magnetic field direction from some controllers, though it's probably not likely that it'll be for both controllers. I wonder if you have a hard metal bias near where your computer is (like iron rafters or some such). Do you have a compass app on your phone? Does it act the way you would expect (reliably point north?). 

In the mean time, I could add an override in the config that lest you accept the magnetometer extents even if it doesn't get the ideal range.

**Comment by HipsterSloth** [comment]
Sorry I missed this issue earlier. I have heard a few reports of some controllers not reporting a usable magnetic field direction from some controllers, though it's probably not likely that it'll be for both controllers. I wonder if you have a hard metal bias near where your computer is (like iron rafters or some such). Do you have a compass app on your phone? Does it act the way you would expect (reliably point north?).

In the mean time, I could add an override in the config that lest you accept the magnetometer extents even if it doesn't get the ideal range.

**Comment by siliciorock** [comment]
No, i don't have any hard metal near.
The compass, an Razer Hydra, and the rest works nice, but the magnetometer have that issue.

I test the magnetometer calibration, with and without the Hydra ON and OFF.

**Comment by HipsterSloth** [comment]
I had another long discussion in issue #232 about drift and magnetometer issues. I would look there for some tips about debugging the magnetometer (and manually tweaking settings). I think ultimately this problem will be fixed when I implement the better magnetometer sample fitting outlined in issue #232. I'm going to close this issue for tracking purposes (since I already have one issue for magnetometer improvements), but please feel free to continue discussion in here about your magnetometer issues and if the advice posted in #232 helps or not.
