### ISSUE TITLE
Found the most ridiculous accessory ever...so I bought it. Want to add support?

### ISSUE THREAD

**Issue by picklefart9** [cboulay/PSMoveService#216]
![0923162137](https://cloud.githubusercontent.com/assets/19967012/18805533/3bd0c69c-81d6-11e6-9d0b-2a056e53f0a1.jpg)
Mad Catz wasn't even crazy enough to make this thing. This is a true first party accessory, the real McCoy. The handles fold out and one twist so you can pretend you're riding a chopper. Has paddle shifters, rear throttle buttons, the whole nine.

**Comment by HipsterSloth** [comment]
I'd love to, but it's going to be added to the end long list of features. The Kalman filter, distortion correction, ds4, client c-api, non ps3eye camera, linux, osvr all come bwfore This would be part of broader support for EXT port attachments. Without some other dev support to help out with this I wouldn't expect this

**Comment by picklefart9** [comment]
Haha no worries. I didn't even expect it. As you say there are more important things you have on your plate. I just had to post - this thing is the epitome of function over form.

**Comment by HipsterSloth** [comment]
Whoops. Hit send too soon (typing on phone). Point being, without some additional dev support, it's going to be months before I can work on this.

**Comment by HipsterSloth** [comment]
It is a pretty cool looking add on. I'd be curious how much of an issue occlusion is.

**Comment by zelmon64** [comment]
@picklefart9 if you'd like to play around with it you can try the FreePIE plugin discussed in [this mtbs3d thread](http://www.mtbs3d.com/phpBB/viewtopic.php?f=139&t=18265&sid=f1ed4d2308c1717c7e6da42e9e12adb0). All the buttons, triggers, paddles and even the twisty bit work fine. The downside is the tracking is inferior to PSMS and integrating it with a game would be tricky (but it is fun to mess around with).

@HipsterSloth I would imagine occlusion wouldn't be much of an issue since its orientation is more important than its position. Any game probably would have a steering wheel in a fixed position. That being said I wonder what the immersion would be like if it was floating all over the place.

**Comment by HipsterSloth** [comment]
I'm going to close this issue since it adds to the clutter of issue tracking. I'll open another issue later about the EXT port support. Feel free to continue discussion in here though.
