### ISSUE TITLE
vibration of hmd at 'test tracking',  what happen?

### ISSUE THREAD

**Issue by poppin12345** [cboulay/PSMoveService#217]
To link with ps move controller 1 & phone 1 (using vridge & riftcat , ps move controller 3, ps3 camera 3, phone 1)
when I run freepie.exe with freepie example script.py default setting , (phone & ps move controller attached to a headset) two units don't be connected together.
For this reason, I found out this contents as below and then maked it translate [0] to [2].
-----------------------------------------------------------------------------------------------------------------
<psmoveservice help tip>

If tracking single controller:

freePieIO[1].x/y/z = Accelerometer data

freePieIO[1].pitch/roll/yaw = Gyroscope data

freePieIO[2].x/y/z = Magnetometer data
---------------------------------------------

Based on vridge tracking mode setting : use magnetometer stability ,I translated this sentences as below

-----------------------------------------------------------------------------------------------------------------
<freepie examle script.py>

def update():
    #Right now, you can only use one axis at a time. 
	freeTrack.pitch = 0 #freePieIO[0].pitch
	freeTrack.roll = 0 #freePieIO[0].roll
	freeTrack.yaw = freePieIO[0].yaw
	#Multiply by 10 for SteamVR use                                            <translation>    
	freeTrack.x = (freePieIO[0].x * 10) ----------------------------->[0] to [2]
	freeTrack.y = (freePieIO[0].y * 10) ----------------------------->[0] to [2]
	freeTrack.z = (freePieIO[0].z * 10) ----------------------------->[0] to [2]
	
if starting:
	freePieIO[0].update += update

In this case, this work make it possible to proceed positional x,y,z movement of right and left nearly & up and down nearly positional tracking.
But it cause terrible vibration of hmd at psmove configtool 'test tracking' setting (steam vr scene similarly).
Please let me know the way to stop this vibration.

**Comment by HipsterSloth** [comment]
This question is probably better asked over here: https://groups.google.com/forum/#!forum/psmoveservice

This issue list is meant specifically for internal problems with PSMoveService and not external plugins like FreePIE. I personally have no experience with the FreePIE plugin so I won't be much help but @zelmon64 or @hawinkse might be able to provide some insight.

If it turns out that the problem with FreePIE is in fact happening due to some internal issue with PSMoveService then we'll open an issue here.
