### ISSUE TITLE
Tracking Color not Sticking

### ISSUE THREAD

**Issue by Cybotive** [cboulay/PSMoveService#224]
The tracking color that shows for each controller doesn't stick, so if i reset the controller it'll show a different color, like red or yellow, but then when in SteamVR it's cyan and magenta. The reason I have a problem with this, is because I either killed the blue in the LED or disconnected it, but red and green work (both cyan and magenta rely on blue... so yeah) .

**Comment by HipsterSloth** [comment]
The tracking color assigned to each controller is doled out in the order the controller connected to psmove service, which is totally arbitrary and leads to problems like this. Someone else was requesting the ability to assign a tracking color to a controller serial number (dedicate a color for their HMD). I think I'll work on that tonight since that'll solve this problem too.

**Comment by Cybotive** [comment]
I ended up just recalibrating the cameras to think red is cyan

**Comment by Cybotive** [comment]
I found #221, so I closed this one.
