### ISSUE TITLE
Move controller not found after pairing

### ISSUE THREAD

**Issue by ariselarisel** [cboulay/PSMoveService#248]
Maybe similar to #135 

Pairing a controller works fine, but afterwards it won't be found. 

- OS: Win8.1
- Setup: as from the hardware-List
- behaviopur is unchanged by:
 - restart of service
 - reboot
 - unpairing/pairing
- Controller's LED will light constantly when service is started and PS-Button has been pressed
- will not show up in PSMove Config Tool under Controller Settings
- Console output:

[console-output.txt](https://github.com/cboulay/PSMoveService/files/533441/console-output.txt)

**Comment by HipsterSloth** [comment]
From the error log it looks likes HID API (the library I use to read data from the controller) thinks that the controller is already in use:

"HID ERROR: Die angeforderte Ressource wird bereits verwendet"
(Google Translate: HID ERROR: The requested resource is already in use)

Are you running the Alpha 5.4 release? If so, try closing PSMoveService and then running test_controller.exe from the console. I'm curious if it gives the same error or not. The test_controller app just tries to open the first controller it finds and then spams the console with data it's reading from the controller. I suspect it will have the same problem, but I want to make sure it's not something else from PSMoveService.

You mentioned you are running windows 8.1? I have had issues in the past with HID API across different versions of windows. I currently do all my testing and development on Win10. When we were first trying to make PSMoveService in Win10 work we had the opposite problem, see here:

https://github.com/signal11/hidapi/issues/231

We have a fork of HID API with a fix for Win10:

https://github.com/cboulay/hidapi/commit/38681c734965636c9fd710dc3898d90aaf923bb9

It's possible that this is causing the opposite problem for you? We don't technically support versions of windows older than Win10 because nobody that is doing development on PSMoveService has older versions of Windows installed anymore. If you were comfortable building from source I could tell you where to make a change to to HID API and see if it fixes the issue for you. If not, I would recommend upgrading to Win10.

**Comment by ariselarisel** [comment]
Yes, I'm trying 5.4.0. test_controller.exe provides similar output:

> \osvr\psmove-service\v0.9alpha5_4_0\Win64>test_controller.exe
Opening PSMoveController...
[2016-10-17 20:05:32.170]: PSMoveController::open - Opening PSMoveController(\\?
\hid#{00001124-0000-1000-8000-00805f9b34fb}_vid&0002054c_pid&03d5&col01#8&359a13
f4&1&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})[2016-10-17 20:05:32.182]: PSMo
veController::open -   with serial_number: e0ae5e4cc9a8[2016-10-17 20:05:32.188]
: PSMoveController::getBTAddress - HID ERROR: Die angeforderte Ressource wird be
reits verwendet.[2016-10-17 20:05:32.194]: PSMoveController::open - Failed to ge
t bluetooth address of PSMoveController(\\?\hid#{00001124-0000-1000-8000-00805f9
b34fb}_vid&0002054c_pid&03d5&col01#8&359a13f4&1&0000#{4d1e55b2-f16f-11cf-88cb-00
1111000030})[2016-10-17 20:05:32.208]: ~PSMoveController - Controller deleted wi
thout calling close() first!


Sadly, win10 isn't an option for me (old sound hardware, and some other stuff unsupported in win10).

If I take a look here: https://github.com/vrpn/vrpn/issues/138 (mentioned in the issue you found), and https://github.com/signal11/hidapi/commit/b5b2e1779b6cd2edda3066bbbf0921a2d6b1c3c0 being the solution, building from source might be an option. I'll however would need a helping hand for this, didn't build anything under windows for years.

**Comment by cboulay** [comment]
The commit you linked to and the commit @HipsterSloth linked to above are effectively the same thing. As our builds have this fix baked in already, then rebuilding with these changes won't help. I think you'd have to undo these changes first.

So follow the build instructions [here](https://github.com/cboulay/PSMoveService/wiki/Building-from-source). Except, after you clone the repository but before you build, edit the hid.c file to undo the change in the above commit (i.e. replace `FILE_SHARE_READ | FILE_SHARE_WRITE` with only `FILE_SHARE_READ`).

This is certainly worth trying because it is one of the only things that's different between newer windows and older windows, but it SHOULDN'T be the source of your problem. My guess is that you have something else, like a 3rd party bluetooth device manager or other PSMove-related software, that's opening up your device exclusively (maybe using an older hidapi).

**Comment by cboulay** [comment]
@HipsterSloth : hidapi master seems to have this change since early March. We can modify our submodule to point from cboulay/hidapi to signal11/hidapi and then I can delete my hidapi repo. Do you see any problems with that? Do you know of any recent changes in mainline hidapi that might break PSMoveService? Can you give it a test? I'm not setup for building in Windows at the moment.

**Comment by HipsterSloth** [comment]
@cboulay I'd be happy to give that a test tonight. I think the file share privilege thing was the only change. I'll post a test build in this issue for ariselarisel.

**Comment by ariselarisel** [comment]
that would be great! amd64 should be enough, btw.

**Comment by HipsterSloth** [comment]
@ariselarisel Could you give this custom build a try: 

[PSMoveService-v0.9alpha5_4_1_custom.zip](https://github.com/cboulay/PSMoveService/files/535390/PSMoveService-v0.9alpha5_4_1_custom.zip)

**Comment by ariselarisel** [comment]
good news for you, and shame for me :)

- your custom build did not change a thing, so locking wasn't an issue (double-check: I also already tried to hexedit the test_controller.exe binary yesterday, which also did not change anything, but was unsure if i really catched the right place)

- I reinstalled the bt-400 drivers for win8.1 found here: http://dlcdnet.asus.com/pub/ASUS/wireless/USB-BT400/UT_USB_BT400_1201170.zip

- Now everything works, even with the write | read share locking.

- I suspect my anti-virus to having intervened at some critical point during the first time i installed these drivers.

So, many thanks from my side, and this is a none-issue for me, now.
