### ISSUE TITLE
Can someone test an OSVR plugin for me?

### ISSUE THREAD

**Issue by robsonswiss** [cboulay/PSMoveService#253]
Hi

Sorry for posting this here.

I want to use this service as explained here: https://github.com/cboulay/PSMoveService/issues/222

So I don't have a functioning PS3 move controller, just cameras and want to start working on an OSVR plugin, is there someone here that can test the plugin for me in case the single point tracking takes a while to complete?

**Comment by HipsterSloth** [comment]
I would happily test it if I had an OSVR headset, but sadly I don't. However I bet someone over in the osvr community has a psmove controller. I would make a post over here: 

https://gitter.im/OSVR/OSVR-Core

Since this isn't technically an "issue" I'm going to close this issue for tracking purposes, but feel free to continue discussion here.
