### ISSUE TITLE
when comes the test version for PSVR tracking

### ISSUE THREAD

**Issue by Liriel-666** [cboulay/PSMoveService#280]
when comes the test release for the PS VR tracking ?

**Comment by HipsterSloth** [comment]
When it's done :).

I'm trying to work on it a few hours each evening. It's the thing I'm spending most of my free time on at the moment. But I couldn't give you an accurate estimate as to when I'll be done with it as I have no idea whether the current approach I'm trying for tracking is going to work or not. I would like to get some functional version of this ready in the next month. But I won't promise anything.

You can follow the commits I'm making related to PSVR stuff here:
https://github.com/cboulay/PSMoveService/commits/hmd_server

I try to post updates here about the work I'm doing:
https://groups.google.com/forum/#!topic/psmoveservice/vXe5DXQDGHQ

For future reference, if you have questions like this it's better to post them to the google group, rather than making an issue. We're trying to make the issues section only for reproducable bugs and features we've agreed about working on. Otherwise this list gets unmanagable really quickly:

https://groups.google.com/forum/#!forum/psmoveservice
