### ISSUE TITLE
led ball replace the 3rd controller and achieve HMD tracking successfully

### ISSUE THREAD

**Issue by pjsy0826** [cboulay/PSMoveService#293]
Some people use the 3rd controller and attach it  to the hmd to achieve HMD tracking.
Actually,it just need the led ball. 
It's much more convenient and ligther.
![img20161124202534](https://cloud.githubusercontent.com/assets/23151145/20612497/8bfd5540-b2f5-11e6-80f2-f921f1066030.jpg)
![img_20161125_094323](https://cloud.githubusercontent.com/assets/23151145/20612498/8bfdc084-b2f5-11e6-856d-b8aec8e390a7.jpg)
But because the PSMoveFreepieBridge need to bind the 3rd controller, it still have to use the 3rd controller to connect the computer first.
Could you please add a new funtion in PSMoveService that we can build a virtual controller,which just use to 
bind the PSMoveFreepieBridge.  In that way ,we just need to buy a led ball instead of a controller.

**Comment by gb2111** [comment]
Hi,
What did you made it from - i mean bulb? I tried few but never got unified lighting.

I have also tried put controller on the back of hmd and then it was much better for my nose :)
However I was not able to calibrate controller and hmd properly. they were always away from me and they were changing distance once I was turning around. so I finally moved it back to front and my nose is suffering. so you don't have this issue?
thanks.

**Comment by pjsy0826** [comment]
@gb2111 I konw what you mean.it usually happened when you use 2 camera or less.  using 4 camera will be better.
Use a 3.3V battery can lightting the led. and you can place the led on the top of your hmd.your nose will feel good.

**Comment by wisockijunior** [comment]
I am using a portable running light, those you attach to your leg and run
at night, it tracks well, and is really smaller that a psmove bulb; I am
thinking in attaching two of them to one gearVR

Att
Renato Wisocki Junior
renato@wisockijunior.com.br


2016-11-25 7:27 GMT-02:00 gb2111 <notifications@github.com>:

**Comment by gb2111** [comment]
@pjsy0826 i understand you have led but how did you get this ball? is this ping pong ball?
did you have issue with calibration as I have described? I mean bulb is on the top of your head and when you calibrate controller you will probably touch your phone. not sure why but when I have like this then when I turn then controllers are making elipse...

@wisockijunior , the problem is that those running lights have directional light. however there can be model that is good for our purpose.

**Comment by Tux0Topo** [comment]
@pjsy0826 I've asked for the same thing a few months ago. I've tried to do the same thing, but never tested it (don't have a real psmove controller). Great work!! :D

**Comment by HipsterSloth** [comment]
A few months ago I was resistant to adding virtual controllers made of just point light sources because we didn't support a tracking algorithm for point light shapes and adding those would require a lot of infrastructure work. Since then I started work on tracking for PSVR headsets, which basically ended up adding in a lot of the framework I was previously hesitant to add for point lights. That said if you are using a spherical bulb like this it's pretty straight forward to add support for that. After I get the psvr tracking sorted out I was planning on working on virtual controllers.

**Comment by pjsy0826** [comment]
@gb2111 I bought it from the oline shop .it just takes 1 dollar.But I'm not sure if it was selling in your place.
you can also use a similar ball like pingpong and put a led in it.
Make sure the camera can catch the color .

**Comment by gb2111** [comment]
@pjsy0826 , can you point me to your model? i must go wrong use of search as I am not able to find anything similar... thanks.
also, you don't face issue if non symmetrical distance to controllers when you turn around?

**Comment by gb2111** [comment]
Actually when I connected controller to back rubber on head it was very comfortable as it removed weight from hmd and nose problem. I would be happy to stay with this solution.
However problem is when I calibrate controller and hmd as I described already. The behavior is very different compared to situation when bulb is near display. When I calibrate they are like already distanced and when I turn around they don't keep same distance from head and make ellipse. 
I appreciate if someone can comment on this as any solution would not work for me...
Personally my solution was working very well for me if not the issue. It's comfortable and any time invested in other bulb exceeds cost of controller.

**Comment by gb2111** [comment]
I made video that shows the issue. If hmd controller and bulb is at same position as hmd then all works fine. When I move it to the back of my head then I can see ellipses as you can see. I left hmd controller visible so you can see where it is. I am not sure how to sort this out. Help!
https://youtu.be/hkk9Z3Ua-5I

**Comment by JanKokalj** [comment]
I was able to track a pingpong ball with diffused LED (in a different project, but it should work here). But I do not understand how do you get IMU data from phone to ps move service ?

**Comment by HipsterSloth** [comment]
I believe the IMU data would go to VRidge on the phone, not to PSMoveService on the PC. PSMoveService would just feed the tracking position to VRidge (via FreePieBridge) on the PC side (Once we support "virtual" HMD tracking). Someone correct me if I'm wrong about how VRidge/FreePIEBridge would handle this.

**Comment by orangy57** [comment]
Wouldn't you only need the light, as FreeTrack doesn't need a PSMove Controller to be used?

**Comment by Tux0Topo** [comment]
@orangy57  Hi!! The implementation of psmove service + riftcat, only uses the light. Other implementations, for example psmove service + rift dk1 (or dk2 with out camera), uses the entire controller to track the exact position and rotation of the hmd.
Freetrack (or Opentrack) uses multiple leds to track position and rotations, but have some limitations.
The best solution out there, is to use both, electronics (gyros + magnetometer) and optical tracking....

**Comment by pjsy0826** [comment]
@Tux0Topo @orangy57 
FreeTrack needs gyroscope and light to track position and rotation of the hmd.
But don't forget, there is already gyroscope in our hmd and our phones. So we just need a light can achieve FreeTrack.  
In riftcat ,there is a choice  that you can choose using the gyroscope in your phone or not.
![qq 20161206124946](https://cloud.githubusercontent.com/assets/23151145/20913553/cde6aa08-bbb3-11e6-88ed-d73e3f3d1b37.png)
![qq 20161206124949](https://cloud.githubusercontent.com/assets/23151145/20913554/cdfa8cb2-bbb3-11e6-8355-12ccb8f2de7f.png)

**Comment by Tux0Topo** [comment]
Sorry... i'm expressed myself very bad.
In psmove service + riftcat, the controller attached to the hmd only gives position, and that's the light only. The rotations are from the phone. Other implementations, as psmove service + rift dk (or others hmd with no positional tracking), use posstion and rotations from the psmove controller.
Freetrack/Opentrack, uses light (or other forms of tracking), that can provide fully position and orientation. But sadly, is very limited with occlusion. Those programs only use 1 camera.

**Comment by Wully616** [comment]
Hey, just to add to the viability of using a led ball instead of a full third controller, I found this usb powered LED ball light today in Discount UK (a pound shop / dollar store).

I still need to test it, due to the colour of the light, I'm not sure if the psmoveservice will track it properly since they aren't one of the standard colours? 
Unfortunately I also only have 1 ps move controller.
They look similar in size, maybe just a bit smaller than the ps move controller led ball. The light is much brighter than the psmovecontroller.

![img_20161206_181922](https://cloud.githubusercontent.com/assets/2709270/20938195/059c96fa-bbe2-11e6-8f81-c5431b3d60f8.jpg)
![img_20161206_181837](https://cloud.githubusercontent.com/assets/2709270/20938196/05a2f09a-bbe2-11e6-8bb9-0a4432b165c5.jpg)

**Comment by pjsy0826** [comment]
@Wully616 you can cover something red on your led ball or use a red pen paint on it, just make the light has a color.It doesn't matter if the color is standard colour or not. In the setting of psmoveservice, you can 
the tracking color of the 3rd controler and change the parameter of the tracking camera. Make sure the camera can track the color of your light and it will work well.

**Comment by HipsterSloth** [comment]
Apologies if this was already suggested in this thread (or implied), but it
just occurred to me that you could do something silly to make an extra bulb
like this work if you have an extra controller. Connect the controller you
would use for HMD tracking to psmove service, so as far as the service is
concerned, it's attached, but then hide it from view. In the color config
for the HMD tracking controller, show it this bulb instead of the psmove
controller and adjust the color filters accordingly. Then attach this bulb
to your HMD. As far as SteamVR/PSMoveService will be concerned it will
think it's tracking the psmove controller. The orientation for the
controller will be wrong, but if you are using VRidge you don't care since
your using the orientation from your phone anyway. At some point we'll
support virtual controllers (i.e. just light sources) so you won't need to
fake it like this.

**Comment by gb2111** [comment]
@HipsterSloth , I did exactly what you say and it works.
However It was not easy for me to get make BULB with unified color so the color calibration will filter whole area, like for PS3 Controller. So I gave up finally.

My problem however was weight of the headset. I solved it easily by attaching controller to the back of hmd which would work perfect if not the issue with asymmetrical rotations. I hope someone can look and advise why it happens. It must be something with VRidge I think...
https://www.youtube.com/watch?v=hkk9Z3Ua-5I&feature=youtu.be

**Comment by cboulay** [comment]
@gb2111 

When you rotate your head about the neck, the HMD isn't rotating in place. It's forming an arc through space. The back of your head forms a much different arc that is not perfectly symmetric with the HMD arc.

I don't know how, and I don't really want to get into it, but there might be a way to account for an offset/transformation from the 0,0,0 point of the rigid body you want to track to the PSMove position. This isn't as simple as adding a vector to the position returned by PSMoveService because it depends on rotation too. I'd say that this is something that should be handled by a 3rd party app or the openvr driver.

**Comment by gb2111** [comment]
@cboulay , I will contact RiftCat and ask if they have anythig with this.

**Comment by zelmon64** [comment]
@gb2111 It should be fixable in the FreePIE script. I'm having a go at it today. I'm adding a calibration section to first calculate the offset between the HMD and the bulb then apply that offset to the position of the HMD depending on the current orientation of the PSMove.

**Comment by gb2111** [comment]
@zelmon64 , thanks for reply.
Yes, that should work. But offset would be only in specific direction as you can see in my video.
Will be waiting for that :)

**Comment by zelmon64** [comment]
@gb2111 Here's a first attempt. I did it using PSMoveFreepieBridge-alpha6-PSMoveService-alpha5 and PSMoveService-v0.9alpha5_3_0 (because I'm behind and thought it would be quicker to update after I added the modifications to the script). Could you point me to where you first mentioned this problem so that we can continue discussing (and ironing out bugs) there (I can't seem to find it). To use this script run it and everything else like normal but perform a calibration by pressing the Move button on the HMD PSMove. During calibration spin around like in your video then face forward and press the Move button again to finish.
[freepie example script with hmdoffset.py.txt](https://github.com/cboulay/PSMoveService/files/636496/freepie.example.script.with.hmdoffset.py.txt)

**Comment by gb2111** [comment]
Hi @zelmon64 ,
That looks great! I will try this evening.
Greg

**Comment by gb2111** [comment]
@zelmon64 ,
I need to wait few days as my phone is in service now... Will update probably late next week.

**Comment by vrgamer** [comment]
Hi @pjsy0826 
With only the led ball, can you choose the different standard colours (cyan, magenta, etc) ? 
Thanks

**Comment by Tux0Topo** [comment]
@vrgamer The light source (led or standard filament bulb) have an specific color (blue/red/green/etc). To make an specific color in the psmove controller, you have multiple leds, and combining their colored lights get you the color. With the current experiment, most of us are trying to reduce weight, reduce cost, and do something simple. So, most of us are gone a use a specific light source, or some white light with some filter to light in the bulb... If you want to do something else, great. But as far as i read about, it's not necessary.

**Comment by gb2111** [comment]
@zelmon64 
its been a while. unfortunately my hmd controller is broken and i cnnot test it.
but I heard it works for someone. so great work!
when I have some time, i will implement shift on the server side.
g

**Comment by wisockijunior** [comment]
cant you just use the phone flashlight instead?

Att
Renato Wisocki Junior
renato@wisockijunior.com.br


2017-02-02 8:56 GMT-02:00 gb2111 <notifications@github.com>:
