### ISSUE TITLE
Other Camera

### ISSUE THREAD

**Issue by liuping001** [cboulay/PSMoveService#298]
Hello! How to support others camera?Any camera can be supported?

**Comment by HipsterSloth** [comment]
At the moment we only support the ps3 eye. Primarily because we don't have a utility yet for calibrating the lens intrinsics  and distortion parameters. Those parameters for the PS3Eye are currently hard coded. However, work is underway to support this. It's one of the next major features I wanted to support.

Closing this for tracking purposes as the question is already covered under issue #115 (though feel free to continue questions on this issue).

**Comment by liuping001** [comment]
Think you
