### ISSUE TITLE
Ps move controllers not appearing in front even when calibrated correctly 

### ISSUE THREAD

**Issue by papalasarou** [cboulay/PSMoveService#313]
Hi I'm having an issue where no matter how many times I calibrate the is move controllers never show in front of me - they can appear to the left or right or above me after I've callibrated, but never in front of me. When I move them they go up and down but never forward or back etc..  I'm using a cv1 and I've tried several different releases no joy - can anyone offer any advice? I'm using two ps eyes and they both pick up the moves and calibrate with no issue etc..

**Comment by papalasarou** [comment]
I should also add doing the press start and Select within steamvr in the latest relatse doesn't fix the issue either

**Comment by fbepyon** [comment]
make sure that when you are hitting the Select/Start you are doing this so that one controller is up against the HMD display.  I ran into something similar with my DK2 last night, and noticed that you need to do your Select/Start when the controller is directly in front of the HMD.  ** Only one controller needs to be used to configure this**

BTW this took a few attempts, and also I did mess up my original tracking pose by doing the Z direction backwards.

**Comment by HipsterSloth** [comment]
Closing old support tickets. If this still a problem please post a support request in the google group:

https://groups.google.com/forum/#!forum/psmoveservice
