### ISSUE TITLE
ROI losing tracking on controllers in >2 camera setups.

### ISSUE THREAD

**Issue by POEDaley** [cboulay/PSMoveService#317]
I'm having an issue with ROI.  It seems to be losing my controllers extremely often and it's making the tracking of the controllers go all crazy.  At first, I thought it was just cause of my posters on the wall that had very reflective surfaces and acting as an imposter, but after turning them around and ensuring nothing reflective was in the way, I had zero improvement.  Using the exact same configuration but just toggling the Disable_ROI to True clears everything up and it tracks beautifully.  See my video below.  I start with ROI enabled, and show how they jump around, and I also show a few trackers and how the tracking boxes constantly lose the controllers even when they remain in view.  I then disable ROI at the end without changing any other setting and you see it's cleared up right away.

https://www.youtube.com/watch?v=CQEujKGOnZk

Thanks,

**Comment by cboulay** [comment]
The ROI is getting stuck. Then the position estimation gets stuck. Then the position prediction, which is used to draw the next ROI, also gets stuck. We need to get out of this cycle.

When the sensor fusion SRUKF is working perfectly then a lost optical tracker (for a few frames) should be compensated for entirely by the IMU and we should be able to rely on its positional estimate to draw the ROI. However, the sensor fusion is not yet working perfectly. Also, more lost frames means a poorer position estimation, so we need to accommodate this type of error anyway.

The simplest solution is as follows:

* Set a flag whenever the optical tracker fails to find its tracked object, or the found object is 'bad' for some reason or another. We have something in place for this with `getIsCurrentlyTracking` but it is not tracker-specific. We need something similar for each tracker.
* If that flag is set, on the next frame expand the ROI. In the future we could double the ROI size for every lost frame, but for now let's just expand the ROI to the entire image whenever tracking is lost.
    * This should either happen in the [arguments to `computeTrackerROIForPoseProjection`](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/View/ServerTrackerView.cpp#L1146-L1151) or in the function itself.

How do we know if we fail to find a tracked object or if it is bad?

1. In [`computeProjectionForController`](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/View/ServerTrackerView.cpp#L1120), we call `computeBiggestNContours`. This gives us the area of each contour. 
    * A drastic change in blob area could be a sign of 'bad' tracking.
    * Or a blob area that is a tiny fraction of the ROI area could also be a sign of bad tracking.
    * Some users have their cameras far away, resulting in tiny blobs, so requiring a minimum blob area is maybe not a good solution.
2. A very large difference in blob center-of-gravity could indicate bad tracking, but I do not think we should use this as a criterion because then it might be difficult to get a tracker to leave a shiny spec on the wall when the true bulb is picked up far away.
3. Maybe someday the sensor fusion SRUKF can return some information about the discrepancy between the state space model and the latest tracked position.

@HipsterSloth , where do you think we should store the per-tracker flag of whether or not the last frame gave a good result?

**Comment by HipsterSloth** [comment]
@cboulay Thanks for the analysis. It was because I was previously having problems with the projection of the state's position lagging to far behind the actual projection I tweaked how we computed the ROI in 6.0.6:

 - If the previous frames projection on a given tracker use the center of that projection for the center of the ROI
- Use the bounding box projection of the filter state to compute the size of the ROI box

This modifed approach worked pretty well for me, but it turns out there were a few bugs that I found this evening after repro'ing Chris's results in a 4 camera setup.  

You had mentioned checking against a flag whenever the optical tracking code fails to find a tracked object. We actually do have this flag on the [ControllerOpticalPoseEstimation](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/View/ServerControllerView.h#L21). There are are a list of these optical pose estimations on each controller, [one per tracker](https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/View/ServerControllerView.h#L188). Unfortunately when computing the ROI I wasn't checking this flag as I should have been but rather asking the controller if it was tracked in general, which is true if ANY tracker can see the controller (not necessarily the one we are computing the ROI for).

I also added a new "min_tracker_projection_area" setting in the tracker manager config (defaults to 16px^2). If we have an ROI region smaller than the full screen and the biggest tracking blob found is smaller than this min size we throw out the result, which will in turn force the ROI full screen next frame.

While implementing the min contour area code I also discovered there was a bug in the projection area calculation for ellipses. Turns out the area was being calculated for the normalized screen space ellipse, which resulted in a super tiny area. This would only really matter for the kalman filter code that uses screen area to decide how much to adjust the trust of the noise measurement.

I like your other ideas about ROI invalidation. Particularly scaling up the ROI region over time when we can't find the blob, rather than just jumping straight to the full video frame. I think once I get the accelerometer issues hammered out of the positional kalman filter I'd like to try out some more sophisticated ROI heuristics. That said, in the mean time the current approach seems to be working ok for me in a 4 camera setup.

I pushed the fixes this evening if you wanted to take a look: https://github.com/cboulay/PSMoveService/commit/2338e86fb0d26f8d4365f0db4cb665e1f9677c35

@POEDaley Would you mind giving this test build a try on your setup to see if it fixes the ROI issues for you? If it looks good I'll make an official build.
[PSMoveService-v0.9alpha6_0_7_custom.zip](https://github.com/cboulay/PSMoveService/files/675203/PSMoveService-v0.9alpha6_0_7_custom.zip)

**Comment by POEDaley** [comment]
I'll certainly give this a go after work today.  I'll report back with my findings.

Thanks for the quick turn around on this!

**Comment by POEDaley** [comment]
I'm blown away at how well it works now.  This is absolutely spectacular.  My constant 50% CPU load is now running at ~15% when all cameras are tracking, and as expected, it jumps up just a little when the tracker loses the controller blob.  Even looking at it on a per tracker view and watching the new larger squares track, it is so smooth.  In game, same experience.  The fact that there is plenty more CPU headroom as well helps the experience even more.

Very well done!! Thanks :)

**Comment by HipsterSloth** [comment]
Awesome. Glad to hear that's all working for you as well. I'll try to get an official release out with this change this weekend.

**Comment by POEDaley** [comment]
Perfect.  At this point, there is very little more I could even ask for out
of this software.  Perhaps the Navi support, but that would just be
something that's "neat".

Thanks again!

**Comment by stoyou** [comment]
I have a configuration with 4 cameras and I have the same observation. The tracking is much better with the new version of the ROI. Excellent work ! thank you

**Comment by HipsterSloth** [comment]
Forgot to close the issue.

**Comment by cbaal83** [comment]
I just want to confirm that this new version work's  *much* better on my 4 camera setup.
Thanks a lot guys!
