### ISSUE TITLE
PSMoveService tried to open morpheus command USB interface by default

### ISSUE THREAD

**Issue by ukos-git** [cboulay/PSMoveService#324]
i am using trinusvr for head tracking etc. is there a way to stop psmoveservice from constantly trying to access the PS vr headset?

when trinusvr is running, the acces to the headset is blocked anyway:

` [2017-01-07 22:19:25.797]: MorpheusHMD::open - Opening MorpheusHMD(USB\VID_054c&PID_09af).
libusb: warning [init_device] could not get node connection information for device '\\.\USB#VID_054C&PID_09AF&MI_08#6&2F675FAA&0&0008': [87] Falscher Parameter.
libusb: warning [init_device] could not get node connection information for device '\\.\USB#VID_054C&PID_09AF&MI_04#6&2F675FAA&0&0004': [87] Falscher Parameter.
libusb: warning [init_device] could not get node connection information for device '\\.\USB#VID_054C&PID_09AF&MI_05#6&2F675FAA&0&0005': [87] Falscher Parameter.
libusb: error [init_device] device '\\.\USB#VID_1415&PID_2000&MI_01#7&2231EA8E&0&0001' is no longer connected!
libusb: error [init_device] device '\\.\USB#VID_054C&PID_09AF&MI_01#6&2F675FAA&0&0001' is no longer connected!
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [winusbx_open] could not open device \\.\USB#VID_054C&PID_09AF&MI_05#6&2F675FAA&0&0005#{19BC54D7-79B5-6F56-81E6-DAC811AD5EEB} (interface 5): [5] Zugriff verweigert
[2017-01-07 22:19:25.914]: morpeus_open_usb_device - Morpheus USB device not found!
[2017-01-07 22:19:25.918]: MorpheusHMD::open - Failed to open MorpheusHMD(USB\VID_054c&PID_09af)
[2017-01-07 22:19:25.922]: MorpheusHMD::close - Closing MorpheusHMD sensor interface(\\?\hid#vid_054c&pid_09af&mi_04#7&18f67db0&0&0000#{4d1e55b2-f16f-11cf-88cb-001111000030})
[2017-01-07 22:19:25.928]: DeviceTypeManager::update_connected_devices - Device device_id 0 (USB\VID_054c&PID_09af) failed to open!`

**Comment by cboulay** [comment]
Does trinusvr do optical tracking of the PSVR HMD? Or just use its IMU (website only says gyroscope but I assume they use more if available)?

**Comment by HipsterSloth** [comment]
Try setting "disable_command_interface" to false in %appdata%\PSMoveService\MorpheusHMD.json. I try to open the command interface by default, I should probably disable that.

**Comment by HipsterSloth** [comment]
@cboulay I believe TrinusVR is working on Positional Tracking for the PSVR.  They have a slot for it in there current TrinusPSVR  tool:

![image](https://cloud.githubusercontent.com/assets/16793853/21748280/df63d756-d535-11e6-9bf2-af0abb9875ef.png)

Not sure what state it's in at the moment. 

In any event, if a PSVR headset is connected the HID device enumerator in PSMoveService picks up head set and opens the it. While opening the HID interface (USB interface 4, used for IMU data) I also try and open the command interface (USB interface 5, used to turn on the lights and such) using libusb. I think it's ok for multiple apps to open the HID interface, but libusb needs exclusive device access. I added a debug toggle to disable opening the command interface, but I forgot  to set it to disabled by default. No real point in opening the PSVR headset by default at the moment since you can't really do anything useful with it in PSMoveService yet.

**Comment by HipsterSloth** [comment]
I made it so that we no longer try and open the command interface by default in this change:
https://github.com/cboulay/PSMoveService/commit/34aebfc7980abfa5083d2ecfc668a6e18cd2dde9

That change will go into the next release. @ukos-git Did setting "disable_command_interface" to true fix your issue?

**Comment by ukos-git** [comment]
sorry for the late reply. thank you. Setting `disable_command_interface` did the trick
