### ISSUE TITLE
compute tracker poses works better on build 5.5.3 than newer versions

### ISSUE THREAD

**Issue by iamapie13** [cboulay/PSMoveService#325]
since I began to use the build 6.0.6-6.0.8 compute tracker poses always gives me weird results, sometimes it doesn't but in certain areas of the room the controller just glitches around, meanwhile in older builds I have no problems whatsoever.

**Comment by HipsterSloth** [comment]
Turns out there was an issue with the lens distortion constants I had checked in that threw off tracking. The lens distortion parameters started actually getting used in 6.0.6+ builds (with lens distortion correction). I just created a new build that fixes these constants and forces the camera settings file to update the distortion parameters (all other camera settings left alone):

https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha6.0.9

There's additional discussion in this thread if you are curious:
https://groups.google.com/forum/#!topic/psmoveservice/hYZFlCxZjJY

**Comment by HipsterSloth** [comment]
@cboulay BTW I'm not sure what a good principled way to compute these distortion parameters is besides running the lens calibration tool a few times and picking the result with the most reasonable looking focal length (closest to the 554px value you hand calculated). Here were three runs I did:

1) Calibration mat ~1meter from the camera:

    "distortionK1": "-0.2814047634601593",
    "distortionK2": "0.87820631265640259",
    "distortionK3": "-0.89476829767227173",
    "distortionP1": "0.00024618027964606881",
    "distortionP2": "0.0072853877209126949",

2) Calibration mat ~1/2 meter from the camera:

    "distortionK1": "-0.13120938837528229",
    "distortionK2": "0.2647227942943573",
    "distortionK3": "-0.17127358913421631",
    "distortionP1": "0.0035981093533337116",
    "distortionP2": "0.00076313311001285911",

3) Calibration mat ~1/2 meter from the camera:
    "distortionK1": "-0.10771770030260086",
    "distortionK2": "0.1213262677192688",
    "distortionK3": "0.04875476285815239",
    "distortionP1": "0.00091733073350042105",
    "distortionP2": "0.00010589254816295579",

I went with the 3rd one as the default. If you want to update to a new set of defaults just make sure to bump  the LENS_CALIBRATION_VERSION constant too:

https://github.com/cboulay/PSMoveService/blob/317396739a96c5ec58cadaffa214fc5e66257cb2/src/psmoveservice/PSMoveTracker/PS3EyeTracker.cpp#L34

**Comment by cboulay** [comment]
@HipsterSloth , I think your approach is fine. That's what I did on my own computer.

NBD, but to keep things clear let's call it 'checkerboard' or something like that instead of 'calibration mat' which is something else we use.
