### ISSUE TITLE
Magnetometer disabled

### ISSUE THREAD

**Issue by TwistedChris** [cboulay/PSMoveService#327]
My magnetometer calibration is grayed out "Calibrate magnetometer disabled", Its causing some really bad tracking issues, any idea how to fix?

Thanks, Chris

**Comment by HipsterSloth** [comment]
"Calibrate magnetometer disabled" sadly means that you are using a PSMove controller with newer firmware that has the magnetometer disabled. Why Sony chose to disable the magnetometer is more recent firmware is beyond me. I previously tried to make a tool that would allow me to write older firmware to it. Unfortunately the DFU mode set report that allows me to write new firmware doesn't appear to work on newer PSMove controllers. It's possible that DFU mode set is still there, but I don't know what the new way to activate it. 

Unfortunately what this means is that you'll get more frequent orientation drift. You can recenter the controller by pointing the controller down the -Z direction of your calibration mat and holding SELECT while in SteamVR.

**To be clear, when you say "bad tracking issues", do you mean orientation drift or the position is jumping around?** 
If the position tracking is bad the magnetometer has nothing to do with that. The magnetometer only is used in orientation tracking. Have you done color calibration on the controller yet? Usually bad tracking is due to poor color filtering.

**Also how many cameras are you using?** 
If you are only using one camera we have to judge z-distance based on bulb size, which is much noisier than if you have two or more cameras and can triangulate the z-distance.

I'm closing this issue for tracking purposes (because this doesn't sound like a new issue). But we can continue the debugging conversation here. If it turns out this actually is a new code issue, I'll re-open.

Also for future reference, when troubleshooting issues, start in the PSMoveService google group: https://groups.google.com/forum/#!forum/psmoveservice. If we determine that there actually is a new code problem, then we file a new issue. Otherwise the issue list gets totally out of control (well, more out of control than it already is).

**Comment by TwistedChris** [comment]
Maybe you'll crack it one day, I've just returned them and got some used ones.

Bad tracking issues: When I turn 180' the controllers seem to disappear behind me almost like i'm holding back to front behind my head, at 90' left they sort of point back to where i'v turned from and have a slight drift to the right, and reversed for 90' right, the controllers seem to track well when I face one direction.

My setup:
4 cams (Mounted high)
Vridge (riftcat)
Galaxy 5
PC:
   8GB ram
   SSD
   GTX 1050 Ti
   AMD 4000 series CPU
   750W PSU

Don't know if any of that info helps?

Thanks for all your help, and I'll go to the group next time ^^

Chris
