### ISSUE TITLE
PSMoveService is not saving my tracker config settings

### ISSUE THREAD

**Issue by muzikaal** [cboulay/PSMoveService#329]
I have 4 ps eyes and 3 move controllers. When do the color calibration on the first camera everything works, it sees all 3 controllers and tracks them. However, cameras 2 - 4 forget the calibration and go back to default as soon as I close PSMoveService. What am i doing wrong? I'm new to this so sorry if this is a dumb question.

**Comment by POEDaley** [comment]
I have noticed the same thing myself.  My Tracker #1 was constantly losing color calibration settings for a specific controller every time.  I didn't notice it as much until I went back and tried to diagnose a shakey controller.  I then tried to do the pose calibration with that controller and found 1 tracker wasn't seeing it.  I re configured that color then everything seemed to work till I shut it all down and started up Steam VR again.  I noticed it was still shakey.  I then realized it was never saving that controller after checking the values for it.

Since then, I've managed to solve it, but instead of systematically doing it, I decided to do a fresh setup of the PS Move Service with the latest version, and realized that after I had moved some cameras around and reloaded my USB controller drivers, my cameras somehow switched to the WINUSB drivers instead of using the LIBUSB drivers.  So I reinstalled that on the cameras and continued with the setup, and it's run fine.

So I'm unsure of what happened exactly, but I suspect it was the WINUSB drivers my computer switched to.  So I would suggest maybe double checking that your cameras are using LIBUSB drivers still, and they are showing up as LIBUSB devices in Device Manager.

**Comment by timewornblade** [comment]
I get an issue similar to this every now and again, I am using 4 cameras as well but 1 and 4 usually lose their values

**Comment by muzikaal** [comment]
Okay i checked the drivers and they were all LIBUSB. I uninstalled them anyway and reinstalled them. It's doing the same thing, the first camera remembers but 2 - 4 forget!

**Comment by gb2111** [comment]
For me as well.

**Comment by HipsterSloth** [comment]
I'll take a look at this tonight. Hopefully the problem is straightforward and I can get a hot fix out shortly. I'll post in this thread when I do.

**Comment by POEDaley** [comment]
Is there anything I can provide to you in regards to logs or data that may
help?

**Comment by HipsterSloth** [comment]
@POEDaley Every time you make a change to the color config for a selected camera it's supposed to save out the changes to the config file for that camera. I'd be curious to see of you open the config file for each of the cameras and then update the color settings if the text editor you opened the config file with reports that the file has changed (notepad++ will do this). If only the first camera is updating this way then that would suggest something is broken on the PSMoveService side.

**Comment by HipsterSloth** [comment]
Well I'm stumped at the moment. I haven't been able to reproduce the problem so far. I'm currently testing in a setup with 4 cameras an two psmove controllers. I've tried setting new tracking colors for both controllers and restarting the service.  Are you guys running Alpha Release #6.0.9? There was a bug in 6.0.8 and earlier where the config version wasn't getting saved correctly back out to the camera config files. In fact would you guys mind looking camera config files to make sure the "version" field is set to "7" and the "lens_calibration_version" field is set to "1".

**Comment by gb2111** [comment]
Me too have not been reproduce exact steps.  Before it was only with 1st tracker. Now I have seen it rarely buy still.If I get something I will post but now it's better to live with this if too hard to spot...


Wysłano z mojego smartfonu w Play
-------- Oryginalna wiadomość --------Od: Guido Sanchez <notifications@github.com> Data: 14.01.2017  09:07  (GMT+01:00) Do: cboulay/PSMoveService <PSMoveService@noreply.github.com> DW: gb2111 <knurgb@gazeta.pl>, Comment <comment@noreply.github.com> Temat: Re: [cboulay/PSMoveService] PSMoveService is not saving my tracker config settings (#329) 
Well I'm stumped at the moment. I haven't been able to reproduce the problem so far. I'm currently testing in a setup with 4 cameras an two psmove controllers. I've tried setting new tracking colors for both controllers and restarting the service.  Are you guys running Alpha Release #6.0.9? There was a bug in 6.0.8 and earlier where the config version wasn't getting saved correctly back out to the camera config files. In fact would you guys mind looking camera config files to make sure the "version" field is set to "7" and the "lens_calibration_version" field is set to "1".

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/cboulay/PSMoveService","title":"cboulay/PSMoveService","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/cboulay/PSMoveService"}},"updates":{"snippets":[{"icon":"PERSON","message":"@HipsterSloth in #329: Well I'm stumped at the moment. I haven't been able to reproduce the problem so far. I'm currently testing in a setup with 4 cameras an two psmove controllers. I've tried setting new tracking colors for both controllers and restarting the service.  Are you guys running Alpha Release #6.0.9? There was a bug in 6.0.8 and earlier where the config version wasn't getting saved correctly back out to the camera config files. In fact would you guys mind looking camera config files to make sure the \"version\" field is set to \"7\" and the \"lens_calibration_version\" field is set to \"1\"."}],"action":{"name":"View Issue","url":"https://github.com/cboulay/PSMoveService/issues/329#issuecomment-272609519"}}}

**Comment by muzikaal** [comment]
Update. I formatted my computer and only installed the basics (chrome, avast, steam, etc.) and then followed the guide. The same thing is happening again! Camera 1 always works and remembers my settings, but the other cameras don't. Another thing that happened before and again now is cameras 2 - 4 can see the psmove orbs is masked mode (by just using the default 32 exposure, 32 gain) but they don't recognize it as a controller when i go to computer tracker poses, an in there is no cross on the orb. I don't know whats going on. Any ideas?

**Comment by HipsterSloth** [comment]
Are you calibrating cameras 2-4 using the same controller as you are for camera 1? Also can you zip up all of the config files in "%appdata%\PSMoveService" as paste them here?

**Comment by muzikaal** [comment]
[PSMoveService.zip](https://github.com/cboulay/PSMoveService/files/709829/PSMoveService.zip)

Yes, I'm using the same controller. I've tried it with all three. I'm new to github, did I post the zip properly?

**Comment by HipsterSloth** [comment]
From your config files it looks like you aren't using Alpha6.0.9: https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha6.0.9. 

That had a fix for tracker config file versioning and bad lens distortion constants. I can tell because your tracker config files are missing the line:

"lens_calibration_version": "1",

That or you said PSMoveService is actually failing to write the latest version of the config files to disk somehow.

Could you:
1) Re-download  Alpha6.0.9
2) Delete the tracker config files: PS3EyeTrackerConfig*.json and TrackerManagerConfig.json

**Comment by muzikaal** [comment]
Wow that's probably it. I'll be sure to test that tomorrow!

**Comment by HipsterSloth** [comment]
I believe this issue is fixed now. There was an issue awhile ago where the exposure or gain wasn't getting saved out. I fixed this some time ago and haven't heard of any new complaints about this issue.
