### ISSUE TITLE
ps move service + leap motion, tracking

### ISSUE THREAD

**Issue by z708z708** [cboulay/PSMoveService#332]
I month I test your project and met with a lot of problems with the tracking of controllers, the main problem is when you work with 4 cameras, they can not transmit 60hz they brake, because of this, tracking turns disgusting, I tried them outweigh differently, I put 2 extra usb 3.0 controller. perhaps just to add to better track a motion to add limes to your project, it works with quality steamvr he works with tracking, but he has a problem with the push buttons, it is poorly panimayu finger gestures. if you add it to your project it is essential to solve the problem with tracking, controllers ps Move could be disassembled and the example here of a project to place a button. 4 or use the controller to move the hands. and for the tracking of the head simply use the camera 1 or a maximum of 2.

Now I'll give you links

http://flrnmrr.com/2016/11/30/arduino-vive-controller-emulation

http://hackaday.com/2016/09/13/bewegungsfelder-is-a-wireless-imu-motion-capturing-system/
https://finch-shift.com/

https://www.youtube.com/watch?v=YfEPdo-ZQkk

https://www.youtube.com/watch?v=Re-G5i5RCRw

I hope my findings will be useful to you, what would improve your project and make it a worthy competitor HTC vive

**Comment by cboulay** [comment]
I don't really know what you're talking about. I think whatever translator you used did a poor job.
If your first language is French or Japanese then you can try those first.

>make it a worthy competitor HTC vive

We will never be able to compete with the Vive tracking system. We are not going to try. We are not yet at the upper limits of how the PS Move can be tracked, but the upper limit is significantly worse than what the Vive is capable of.

**Comment by HipsterSloth** [comment]
Thanks for those links.

However I agree with cboulay. It's not a goal of this project to create a competitor with the Vive tracking system. We simply want to make PSMove controller tracking as good as we can make it with existing consumer hardware like the PS3Eye and (eventually) other web cams. These devices are nice because they are cheap and accessible. 

Integration with the leap motion camera is an interesting idea, but I worry that it would be hard to find the right gain and exposure settings that would work for tracking hands and the and the psmove bulb. That and we already have so much work left just trying to get the PSMove controller working well with existing PS3Eyes I don't think we could look into this possibility anytime soon (since we do this work in our free time).

While I enjoy playing with microcontrollers like the Arduino, I think that really limits the audience of people that can use this library. It was super interesting reading about the "arduino-vive-controller-emulation" project you linked. I did not know about the BNO055 IMU (https://www.adafruit.com/products/2472). That's really cool that it does the sensor fusion work on the chip. I sure wish that chip existed in the PSMove controller as it would have greatly simplified getting the controller orientation working.

Since there is not really a specific issue here I'm going to close this. But feel free to either continue commenting here if you like, If you are having trouble getting tracking to work, make a post over at the google group: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!forum/psmoveservice. People can help you diagnose tracking issues there.

**Comment by z708z708** [comment]
I just suggested that you look at the experience of others, and not much to review execution step aside gyroscopes and magnetometers, as they work more stable than the camera.

**Comment by z708z708** [comment]
you just see the difference in the making and you will realize that you need a little to alter your solution. eg use 4 or 5 ps move

**Comment by z708z708** [comment]
www.ximmerse.com/goods-5.html

**Comment by HipsterSloth** [comment]
Let's pretend for the moment that I wanted to support leap motion tracking of the psmove controller. The next question to ask is how it would rank among the other features that people want. 

Currently my attention is pulled between:
* Fixing bugs and UI problems
* Troubleshooting
* Finalizing DualShock4 support (which I need for my day job)
* Finalizing PSNavi support

On the backlog:
* Getting the Kalman filter working well (improves tracking quality)
* Adding support for other web cam types
* Improving SteamVR support (In VR controller settings)
* PSVR support
* Adding support for linux
* Adding OSVR support
* And a dozed other things on the issues page I'm forgetting

"you will realize that you need a little to alter your solution"
This is not a small alteration. This will easily be weeks of work because I do this in my free time and can only work on this a few hours each day. Sure you could make the argument that leap motion tracking ranks higher than some features (OSVR support or PSVR support for example). But even with the stuff I currently working on just trying to get the controllers working on tracking well I still have a few months of work on my plate. 

If you think this is a great idea then by all means feel free to fork this repo and implement support for this. I'm happy to provide guidance on how to get started. But my time is pretty well spoken for at this point with just trying to get the features we have already commited to working correctly.
