### ISSUE TITLE
PS move rotational drift

### ISSUE THREAD

**Issue by DoctorGLaDOS** [cboulay/PSMoveService#334]
Recently I bought two brand new PSMove controlers. I'm using a 3 PS3eye setup and it seems to be giving me a decent positional tracking experience, however both seem to drift counter-clock wise even after Gyroscope calibration. Also Magnetometer is disabled. Are my units defective ?
I have also tried to test it on Ipisoft recorder (motion capture software that supports PS3Move) and because of the lack of Magnetometer it seems to be impossible to calibrate there.

**Comment by cboulay** [comment]
Sorry to be so terse, but please [search](https://github.com/cboulay/PSMoveService/search?q=magnetometer+disabled&type=Issues&utf8=%E2%9C%93).

**Comment by DoctorGLaDOS** [comment]
You are right I searched for keyword drift and not Magnetometer my bad

**Comment by cboulay** [comment]
It's not entirely your fault. We haven't setup issue templates and GitHub's search doesn't align very well with what we are used to from other sites' searches. I would also like it if GitHub had the ability to merge issues.

It's a bit frustrating because we get the same questions over and over (this particular question has only popped up a few times, but the last one was 3 days ago) and it becomes difficult to keep track of the distributed information.

I'm going to try to make that a little better. If you have any comments on how that can be done then please feel free to post them in #335 

Also, if you feel the Wiki could use this information and you know where to add it then please do so.
