### ISSUE TITLE
Should we turn controllers off (disconnect) on Service exit?

### ISSUE THREAD

**Issue by MHDante** [cboulay/PSMoveService#340]
If the adapter remains plugged into the PC, the controllers continue to drain battery.

**Comment by cboulay** [comment]
Bluetooth devices connect to the host PC, not to apps. Usually it isn't up to an app to disconnect a device.

It usually isn't up to an app to pair a device either. The only reason we do it with the PSMove is because it is incredibly difficult (but not impossible!) to pair in Windows using the Windows bluetooth control panel.

I don't think there should be an auto-disconnect when PSMoveService exits because there is no symmetrical auto-connect when PSMoveService starts, and who are we to say that someone is done with their PSMove controller? I would prefer to leave it up to the user to disconnect it with their OS.

However, while disconnecting the controller with the OS is easily done in MacOS and Linux, it is not so easy in Windows. At least, it wasn't last I checked. When I manually disconnected the controller in the bluetooth control panel it also 'unpaired' the controller. And holding the PS button for 8 seconds seems to do something but it also has undesirable side effects, if I remember correctly. Can someone confirm there is no way to use buttons or the Windows interface to disconnect the controller?

If it's true then there is probably good reason to add a button the the config tool to disconnect the controller. Unfortunately, I don't know what command to use to disconnect (/turn off) the psmove. You can try scanning the psmove reverse engineering docs [here](https://github.com/nitsch/moveonpc/wiki) to see if there are any starting points.

**Comment by MHDante** [comment]
The device can be disconnected by power-cycling the bluetooth adapter. (Or enabling+disabling the bluetooth radio).

I took a look at [PSMoveAPI's implementation of psmove_disconnect](https://github.com/thp/psmoveapi/blob/e3c907056d17e16f643597e8c513cebd57ff1327/src/psmove.c#L2149), and I found that they use hid_close() to disconnect a controller. (Which might mean that there's no on-board disconnection mechanism). Furthermore, I'm unsure if this turns off the controller itself (it also gets called in PsMoveController::close().

As for the need for auto-disconnection, It beats having to hold down the move button for 10 seconds.

**Comment by cboulay** [comment]
We also use `hid_close()`, which closes the app's hold on the controller but does nothing to the PC<->Move connection. The Move is still connected. I don't know of a way to auto-disconnect, and we're not going to code in something to cycle the bluetooth radio.

I think when I used to use Windows and I would turn the Move off by holding the button for 10 seconds, I couldn't reconnect again without restarting the PC and/or re-pairing through the app. Is this still the case? Sorry I'm mostly a Mac user these days.

**Comment by MHDante** [comment]
The 10 second disconnect now allows re-pairing by pressing the PS button. I do recall what you're mentioning, but in an older version PSMove-Unity5.

You're right in that it'd be ridiculous to power cycle the radio. And I agree with the notion that an app shouldn't be in charge of connect/disconnect.

Given that it's a design choice, I'll close the issue.
