### ISSUE TITLE
disable orientation for hmd tracking controller

### ISSUE THREAD

**Issue by gb2111** [cboulay/PSMoveService#341]
Hi,
My controller just got broken and showing same direction, it seems only direction works but no gravity, and just shaking... so pretty useless as controller but still works as hmd tracking. The problem is that even tough it points to one direction, it is shaking continuously which translates to shaking of view.  Therefore I would like to introduce parameter to totally ignore its orientation so I will avoid shaking. Perhaps as another type of orientation filter?
Please let me know if you agree.

Anyway its interesting. In one day, one controller got gravity broken (orientation works). Other controller I need to re-calibrate orientation each time. If I re-run config tools it is rotated 45 degrees left. It was working almost from the start in past. I have not done any upgrades recently...

Anyway I think that even if I have working controller I can still benefit from disabling orientation on hmd controller.

**Comment by HipsterSloth** [comment]
I think you might be able to get the effect you want with the "PassThru" filter. That filter just takes the raw optical orientation and returns it back out without any filtering. Since the PSMoveController has no optical orientation it should just return the identity orientation constantly. If that doesn't work I'm fine with adding "disabled" filter.

**Comment by gb2111** [comment]
it sound like what I just described :) otherwise what could it be that PassThru is doing based on ur description :)
i should check first what's available. thanks.

**Comment by gb2111** [comment]
yups. PassThru does the work...
