### ISSUE TITLE
Lots of CPU usage and laggy/shotty Bluetooth Connection

### ISSUE THREAD

**Issue by MysticSurge** [cboulay/PSMoveService#347]
I am using a Exon E5 Processor (Might be the issue)
I am finding that the configuration tool is using up 25% of my CPU at times and can take up to 10 min to load the next menu item

The Controllers wont light up they will rarely and only for a short period of time

The tracking seems to be very laggy

The cameras will only display at around 2-5FPS i am using 4 PS3Eyes

Here is some DxDiag info
[DxDiag.txt](https://github.com/cboulay/PSMoveService/files/728681/DxDiag.txt)

I seriously hope that this can be fixed and if its my hardware oh well I just wasted 85$

**Comment by cboulay** [comment]
Start by reading [here](https://github.com/cboulay/PSMoveService/wiki/Troubleshooting-(Windows)#general-weird-camera-behavior-clean-camera-driver-reinstall).

**Comment by MysticSurge** [comment]
Should I plug each Eye into a different port because currently i am using a USB 2.0 Hub

**Comment by MysticSurge** [comment]
Another issue I noticed last night was that the Magnetometer Configuration wasn't updating the rotation of the device it did for a few seconds (Very laggy updated its position every 5-7 Seconds) and then the light on the top of the controller went out and it wouldn't update the orientation of the device at all

**Comment by cboulay** [comment]
Having all 4 cameras in 1 hub will definitely not work. Try moving your cameras into different ports directly on the computer. Start with one camera. Add another to see if things are still smooth, moving it to different ports as needed.

When it's laggy nothing will work properly. It's hard to diagnose. Sort out your camera issues first to get things working properly then you can start to investigate any calibration issues, if they still exist.

**Comment by MysticSurge** [comment]
Alright Reinstalled drivers all cameras have a seperate port now and no conflicting devices should eb plugged into the Hub

but still PSMove COnfig Tool is taking a hell of a long time to load to the main menu

**Comment by HipsterSloth** [comment]
Sounds like classic USB root hub bandwidth saturation.  If psmoveconfig tool is taking a long time to start that usually means it's stalling trying to connect to PSMoveService, which is in turn stalling trying to open the cameras. 

Before attempting to run PSMoveService, run test_camera.exe. That tool should open up all available ps3eye cameras. If the video windows aren't running at 60fps, then you likely have too much data going through a root hub. Someone had a similar issue recently here

https://github.com/cboulay/PSMoveService/issues/331
"The "Device id 0 closing due to failed read" error for controller means that the USB bandwidth is probably getting saturated on that root hub. You likely have your USB bluetooth adapter on the same USB root hub as you PS3EYECameras. You can tell which devices are connected to which root hub either by using the windows device manager or using the "USBView" tool found here: http://k0lee.com/dc3000/usbts.htm

![roothub](https://cloud.githubusercontent.com/assets/16793853/22313759/173246aa-e313-11e6-8484-df0f2eee00e6.jpg)

If this is in fact the case for you, try moving the bluetooth adapter to a different USB port and then see if that puts it under a different root hub."

**Comment by MysticSurge** [comment]
Actually just found the issue I think the Bluetooth Adapter is too slow I unplug it and the cameras frame rates go back up to around 30-60FPS the configuration tool is working a lot better now and its not using up as much CPU as it has before Its strange though why would a slow bluetooth adapter = camera FPS to be slow as well as CPU performance to increaser

does anyone recommend a fast bluetooth dongle or Adapter that would work with 3.0 on Win 10?

**Comment by HipsterSloth** [comment]
I use the ASUS BT400. That said, even a good BT dongle can still be an issue if it's on the same USB root hub as your cameras. If the bandwidth is already close to maxed out on a root hub, you can push it over the edge once you start reading controller data (happens automatically with PSMoveService).

**Comment by HipsterSloth** [comment]
Closing old support tickets.
