### ISSUE TITLE
DualShock 4 orientation very wierd

### ISSUE THREAD

**Issue by Dylansabi** [cboulay/PSMoveService#360]
It may just be my controller, but do any of you experience that the orientation of the DS4 is messed up? 

When I shake the controller around it ends up in a very different orientation than my controller. This doesn't happen with my Move controller. Also when I put it down it still slowly moves downwards. I don't really see anything to calibrate the orientation.

I really want to know if it's just my controller or if there's something configured wrong so can anyone help me?

**Comment by HipsterSloth** [comment]
It's sadly not your controller. The DS4 only has accelerometer and a gyroscope, but no magnetometer. This means it's more prone to drift than the PSMove controller is. That and my orientation filter could be better. I try to correct the yaw drift using the lightbar, but it's hard to get that working right without it adding too much jitter. You can recenter the controller by holding down the OPTIONS button while pointing the controller forward. 

Which orientation filter are you using for the DS4 by the way?

**Comment by Dylansabi** [comment]
I have tried every filter. I don't remember the full but I am using the 'something something ARG' filter. 
I've tried out every filter and they all seem to do the same except the first one which doesn't do anything.

**Comment by HipsterSloth** [comment]
The "ComplementaryOpticalARG" doesn't do a terribly great job using the optical yaw we get from tracking to fight drift. The "OrientationKalman" is probably best for the DS4 but you need to run the "Calibrate Optical Noise Tool" first to generate a good tracking noise curve.  DS4 tracking only really only works well two front facing cameras that are relatively close to each other so that they can see the tracking bar at the same time.  At some point I need to make a video showing best practices for using the DS4.

That said, it's definitely not in a state yet where I would consider it super great. That's actually why I haven't announced it as "officially supported" yet. It technically functions, but the DS4 filters still needs some work.

**Comment by Dylansabi** [comment]
I will try that calibration when I buy more cameras.   Thank you for your help!

**Comment by Dylansabi** [comment]
Good luck with developing the software for the DS4
