### ISSUE TITLE
Windows 10 with Bluetooth Dongle failed to find bluetooth

### ISSUE THREAD

**Issue by lonestar790** [cboulay/PSMoveService#361]
I have been setting up the service and everything is to your spec. I have installed the dongle, and it is uses the supplied drivers (not the Win 10 default). It is working with every other device that I pair with it. When I have it activated and run the service get the following report:

 bluetooth_get_host_address - Failed to find a bluetooth radio

All of the unit tests that are included in the package work. The Move controllers respond and the video links are up and working. I just can seem to connect the move controllers. What am I missing?

I also tried the last two alphas just to make sure that the service update had not impacted the setup.

[2017-02-15 23:07:58.389]: bluetooth_get_host_address - Failed to find a bluetooth radio

I am also getting- I have two PS3 cameras in my setup. I assume this is all of the times I connected/installed the cameras.

\AppData\Roaming\PSMoveService\TrackerManagerConfig.json"
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
[2017-02-15 23:07:58.421]: PS3EyeTracker::open - Opening PS3EyeTracker(USB\VID_1415&PID_2000\b1_p9, camera_index=0)
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent
ps3eye::PS3EYECam::getDevices() found 2 devices.

Thank you for your time. I am excited about this project and hope to use it if I can make it past this one.

**Comment by HipsterSloth** [comment]
Sorry for the trouble and thanks for the detailed logs and the investigation.

Which bluetooth adapter do you have? 

If it's the Asus BT-400 (the one recommended in the hardware wiki) you actually DON'T want to use the supplied driver and DO want to use the Win10 default ones. Using the supplied drivers has led to exactly this problem. Why using the supplied drivers breaks the windows find bluetooth radio API is unknown to me.

Also the following error:
libusb: error [windows_get_device_list] program assertion failed - existing device should share parent

.. actually isn't important. It's effectively log spam from libusb that unrelated to the PS3Eye camera, but is unavoidable if we want other useful libusb logs.

Also for future reference, when asking troubleshooting questions, please post to the PSMoveService google group first: https://groups.google.com/forum/#!forum/psmoveservice. If we determine there that there is an actual bug, then we'll file an issue. We have to be militant about routing issues to the google group because otherwise the issues list quickly gets unmanageable.

I'm going to close this issue for tracking purposes, but please feel free to continue the conversation here.

**Comment by lonestar790** [comment]
Thank you for the response. I will remove the drivers and attempt the Windows 10 defaults. I will report back asap. Wish me luck.

Anthony Shumate

**Comment by HipsterSloth** [comment]
Whoops, forgot to close issue like I said I would before...

**Comment by lonestar790** [comment]
The based Windows drive did get me to the next step. I am working on the sampling section. Everything is tuned with the mask being seen, but I can only get it to sample station one. Do you have a trouble shooting section about this process? Thank you again.

A

**Comment by HipsterSloth** [comment]
By "sampling section" I assume you mean the [tracking pose calibration](https://github.com/cboulay/PSMoveService/wiki/Tracker-Pose-Calibration)? 

-Are you sure the [color calibration](https://github.com/cboulay/PSMoveService/wiki/Color-Filter-Calibration) is set right? Sometimes if the exposure or gain are set too high you can get patches of light  that get confused for your tracking bulb. 

-You might also try assigning a different tracking color for the controller. 

-Finally it's also possible that the surface you have place the controller on isn't flat. The tracking pose calibration tool tries to use the accelerometer in the controller to tell if the controller is pointed straight upward. If you are certain it's pointed upward and the sampling timer keeps resetting, go ahead and hit the "trust me, it's stable" button for force sampling at that location.
