### ISSUE TITLE
steam vr

### ISSUE THREAD

**Issue by joshdean985** [cboulay/PSMoveService#364]
no lights on controlers unless tests are running and controlers dont show up in steam 

plz help!!!

**Comment by HipsterSloth** [comment]
I answered your question on the google group here: 
https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/psmoveservice/NNjmYoS9N4A/AK15OTuRDQAJ

For future reference, don't open an issue here until we've had a discussion on the group first. If we determine there that there is an actual bug, then we can file an issue. Otherwise this issues list gets out of control.

**Comment by joshdean985** [comment]
In the settings file there was nothing so I added the line and am currently using with out headset till it arives

Sent from my iPhone

On 17 Feb 2017, at 8:13 pm, Guido Sanchez <notifications@github.com<mailto:notifications@github.com>> wrote:


Closed #364<https://github.com/cboulay/PSMoveService/issues/364>.
