### ISSUE TITLE
Steam VR Setup

### ISSUE THREAD

**Issue by magadan** [cboulay/PSMoveService#366]
Hello, a question about documentation in Wiki

On this doc: https://github.com/cboulay/PSMoveService/wiki/Steam-VR-Setup

In " Configure steamvr.vrsettings
Open C:\Program Files (x86)\Steam\config\steamvr.vrsettings"

The file is created automatically by "SteamVR_InitialSetupWin64.bat"  or i need to create a empty file on the folder after run the .bat ?

**Comment by magadan** [comment]
This is my config folder after run the .bat and driver .bat...

no steamvr.vrsettings  file !

[http://i.imgur.com/VHRTI95.jpg](http://i.imgur.com/VHRTI95.jpg)

**Comment by magadan** [comment]
Found the new location: C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\settings

Pls update the wiki. Thanks

**Comment by HipsterSloth** [comment]
I believe the settings file in `C:\Program Files (x86)\Steam\steamapps\common\SteamVR\resources\settings` is the defaults file in the event that no steamvr.vrsettings file exists. You have to make the steamvr.vrsettings file if none exists. The SteamVR_InitialSetupWin64.bat does not make that file since it could have other settings in there unrelated to psmoveservice. I should make that more clear in the wiki though. 

Also there is a newer version of OpenVR out now (1.0.6) that changes a few things about you register plugins with SteamVR. After I finished up with the C-API work I was doing update the psmove plugin to use openvr 1.0.6 and fix up the SteamVR_InitialSetupWin64.bat script. I'll probably do another documentation pass then too.

**Comment by magadan** [comment]
ok, thank you.
