### ISSUE TITLE
Body positional tracking?

### ISSUE THREAD

**Issue by jonnypanic** [cboulay/PSMoveService#404]
I was messing around with latest release, trying to set the controller tracking colours, when I noticed the tracking was way off, but actually locked to my chest and hands. I could walk backwards and forwards, raise my hands up and down, and the tracking would follow them, without the controllers.

Is this normal behaviour? If so, can it be used for positional tracking? 
I have tried to reproduce it, but haven't succeeded. I use a Pimax with no positional tracking so something like that that could track body movement would be great.

**Comment by zelmon64** [comment]
Firstly these sort of questions should be asked in the google group and then be made into an issue only if a flaw or modification to the code has been identified. Could you please close this issue?

[https://groups.google.com/forum/#!forum/psmoveservice](https://groups.google.com/forum/#!forum/psmoveservice)

Secondly the possibility of adding positional tracking to these HMDs (this and the deepoon) has already been discussed multiple times on both here (in similar closed issues) and the google group.

Lastly I'm a bit confused by your description of the current state of your tracking. You say that the tracking was locked to your chest and hands and that the tracking would follow your hands but without the controllers. When you make a post on the google group could you please elaborate on this so that I may try to help?
