### ISSUE TITLE
PS Service Config Tool failed to pair

### ISSUE THREAD

**Issue by EricH456** [cboulay/PSMoveService#421]
I am trying to pair my ps move controller to my pc using ps service but when i click pair 
"AsyncBluetoothPairDeviceRequest - Failed to find a bluetooth radio"
"ServerRequestHandler - Async bluetooth request([Pair] ID: 0 Conn: 0) failed to start!"
this pops up on the control prompt but i have a bluetooth usb in. the video i am following for setting this up is     https://www.youtube.com/watch?v=QEraN1r_5Nw&t=210s     everything is working fine until i get to the pairing of the controller.

**Comment by cboulay** [comment]
-For some BT dongles, they work with the default Windows drivers but not with the drivers that come from the manufacturer. Try uninstalling the drivers from the manufacturer.
-Not all BT dongles work.

I'm going to close this issue because it's not something that can be fixed in PSMoveService. Feel free to continue commenting.

**Comment by EricH456** [comment]
how do i do that, and it was a bt device used for a ps3 controller before so idk if that matters

**Comment by cboulay** [comment]
I think you'll be better off doing a google search on how to uninstall BT drivers. My guess is that you (1) remove the device; (2) uninstall the device from control panel, (3) uninstall any software from the manufacturer, (4) restart, (5) plug in the device and let Windows handle it.
