### ISSUE TITLE
PsMoveConfigTool not connecting to server

### ISSUE THREAD

**Issue by felipavil** [cboulay/PSMoveService#452]
Every time I open PsMoveConfigTool, it comes up with the "Connect" window with two boxes with "localhost" and "9512". When I click connect, it says "Failed to Connect to PsMoveService!" I've tried changing the port number, and the farthest I've ever gone is a "Status" window saying "Connecting to PsMoveService..." and a button saying Exit. The window never changes. I've read some Google Forum posts saying that they uninstalled something called Unified Remote. I'm sort of a noobie at this level so I don't really know where to go from here.

**Comment by HipsterSloth** [comment]
Since this is a troubleshooting question we usually prefer that people post those issues on the google group first. If it turns out that this is an actual bug, then we'll create a new issue for it.

That said, I'm pretty sure your particular issue has to do with PSMoveService getting stuck trying to open all available PS3EYE cameras and controllers. The config tool is then getting stalled waiting for a connection reply from PSMoveService, which will never respond. This is usually caused by USB bandwidth saturation (too much traffic on a usb root hub). You might try moving around which USB ports your PS3EYE cameras are connected to and see if that helps.

If the above suggestion doesn't fix your problem, please post this to the google group and we can continue troubleshooting there.

**Comment by ihavenoidea64** [comment]
I can not connect to the server after trying everything, I'm tired of it and need a solution.
