### ISSUE TITLE
Using PS Move service in another application written in NodeJS

### ISSUE THREAD

**Issue by MatisiekPL** [cboulay/PSMoveService#493]
Hello.
I really want to create application in my favourite programming langugage, which will handle all positions of controller. I red that any application can use service via network. But I can't find any documentation about protocol. Can you find or write any document about network packages that I should use to comunicate to service?

Thanks, 
Mateusz Woźniak

**Comment by cboulay** [comment]
The easiest way would be to write a C-wrapper using the CAPI:
https://github.com/cboulay/PSMoveService/blob/master/src/psmoveclient/PSMoveClient_CAPI.h

Writing a doc to describe the network protocol would be a huge undertaking, especially because the network protocol uses protobuf and is expected to be unpacked by something using protobuf.

**Comment by cboulay** [comment]
No follow-up so I guess you've moved on. Feel free to re-open if you want to discuss this more.
