### ISSUE TITLE
Official IRC/Discord/whatever?

### ISSUE THREAD

**Issue by craftxbox** [cboulay/PSMoveService#532]
Im wondering does this project have an irc or discord server or any other type of instant chat service in use for communication publically

**Comment by cboulay** [comment]
There is a psmoveservice Slack, but it's been around for a couple years and has exactly 0 messages.

I prefer users keep to the GitHub issues and the [google group](https://groups.google.com/forum/#!forum/psmoveservice) because they are a lot easier to search for other users with the same questions.
