### ISSUE TITLE
how do i set up / install the sevice 

### ISSUE THREAD

**Issue by hani910** [cboulay/PSMoveService#57]

**Comment by HipsterSloth** [comment]
I'm working on documentation for this now so your question is very timely. As soon as I get this done (most likely by tomorrow) I'll update this issue.

**Comment by hani910** [comment]
thank you

**Comment by HipsterSloth** [comment]
I finally finished my first pass on the setup documentation: https://github.com/cboulay/PSMoveService/wiki

One important note, there appears to be a bug with with tracker pose calibration using HMD coregistration. See issue #60. I'm going to try and get that fixed by tomorrow evening and get a new binary release up.
