### ISSUE TITLE
Q: PSVR tracking code/demo

### ISSUE THREAD

**Issue by mick-p1982** [cboulay/PSMoveService#578]
Hello, I'm interested in tracking PSVR for a standalone product. I saw that PSMoveService used two PS3 cameras, which I have on hand, and so I wondered about tracking the headset: 

https://www.reddit.com/r/PSVRHack/comments/5cpi4x/psvr_tracking_progress_report_in_psmoveservice/

The PSMoveConfigTool says it can't see HMDs, so I'm not sure if I can demo it, or if the feature is enabled. I don't know what is required to discover the head set, but since PSMoveService is for PlayStation specifically I'd hoped it could find the device.

"Failed to open MorpheusHMD(USB\VID_054c&PID_09af)"

I'm curious if the code works/exists? And if so would like to combine it with code from PSVRToolbox to use the headset without anything like SteamVR that I can't figure out myself (I guess you need a Steam account or something.)

I can dive headlong into the project (I was going to implement tracking myself anyway) but I thought I should ask for a second option first, even though an Issue tracker is not the ideal forum :)

EDITED: Found this (https://www.youtube.com/watch?v=L0cDhh7qmwY) and this (https://github.com/HipsterSloth/PSVRTracker) ... maybe I'm in the wrong place. https://github.com/HipsterSloth/PSVRTracker/issues/3

**Comment by HipsterSloth** [comment]
Yeah I had started implementing PSVR support in PSMoveService a long time ago but it soon became clear that it was going to be a sizable undertaking and I didn't want to disrupt PSMoveService code base more than I already had trying to get it working, so I made another testbed project for it. I'm going to close this issue here and continue the discussion on the PSVRTracker tracker issue you made.
