### ISSUE TITLE
Move controller on HMD for positional tracking?

### ISSUE THREAD

**Issue by hani910** [cboulay/PSMoveService#59]
would it be possible to mount a move controller on a headset to use it for positional tracking

**Comment by cboulay** [comment]
Do you have a particular headset in mind? Would this be used for existing software or for custom software?

I don't think there'd be any way to trick any software that uses the Oculus SDK into recognizing the DK1+PSMove as a DK2. Similar for GearVR.

It might be possible to write an OpenVR wrapper around the Oculus SDK and insert in that wrapper the PSMove controller as the positional part of the HMD. This approach might also be used for other non-tracked headsets, wrapping each headset's driver.

I'm not sure how this would work with Android/Cardboard. I've never looked at any Cardboard SDK. PSMoveService could run on a nearby PC, getting the controller pose, and an android client could read the pose over the network (wi-fi delay). From there, I'm not sure how this would be used by the game. My guess is that you would need a custom App that knew what to do with the PSMove data.

That being said, I don't think this is in the realm of things we want to get involved in right now. Supporting individual HMDs/SDKs would be a huge burden and there are other more pressing things to work on at the moment.

I'll leave the issue open for now in case @HipsterSloth wants to comment.

**Comment by HipsterSloth** [comment]
Sorry I meant to comment on this sooner. 

You can write a C++ game now that uses the client API to get the controller poses and treat one of them as the head pose. Since it's coming over the network there is definitely some latency so you'd really want to predict where the headset would be based on the network round trip time / 2. However, it will be difficult to do prediction at the moment because the physics data (linear and angular velocities) I'm sending over are garbage and I haven't had a chance to figure out why yet. I want to fix that soon because it effects the SteamVR plugin. Once that's fixed then this would theoretically be possible.

Long term it'd be interesting to expand the client API to combine networked data from one or more controllers and fuse that with local IMU data on the GearVR/Cardboard. But like cboulay said, we've got a lot on our plate at the moment.

**Comment by cboulay** [comment]
I'm just going to close this because realistically it's not something we're ever going to support directly, but we're more than happy to provide advice to others that are trying to use make a custom client that uses PSMoveService in this way.

**Comment by xMindweaverx** [comment]
#134 - @HipsterSloth - Just referencing back to where I was still getting rotational spin with the PS Move as a positional tracker. I recalibrated right after I posted that and played a few rounds of Fruit Ninja and i didn't notice any rotation.. So, I think I know where the problem lays.. What happens when the hmd and controller leave the trackers and then re-enter? I think this is when I'm losing rotation calibration. What do you think HipsterSloth and @cboulay ? I'm going to test again tonight with audio shield. I just need to pick up another PS Move Controller. 

Also, this is a small request and I hope it's simple, but can you turn the skins off on the third controller and maybe just leave the light/bubble? This would be a nice feature to go along with @hawkinse 's method of using a PS Move for HMD positional tracking. Thanks again guys an awesome work!

**Comment by HipsterSloth** [comment]
@xMindweaverx As far as PSMoveService is concerned exiting and re-entering the tracking volume shouldn't affect calibration. We only update the hmd tracking volume and ps3eye tracking camera transforms after the calibration tools run. Maybe steamvr is resetting it's tracking volume? 

As for the for the controller skins, that should be possible. You specify what controller model you want to use per controller, see [here](https://github.com/cboulay/PSMoveService/blob/master/src/openvr_plugin/driver_psmoveservice.cpp#L1122-L1126). It's actually possible to define per mutable sections of the controller geometry. You can create a .json file that let's you define sub-meshes and which property they permute on (or animate with). I've wanted to do this to make the controller trigger animate in SteamVR. That said it'll be at least few weeks before I could get to this feature.

**Comment by Bungpiece** [comment]
@xMindweaverx are you using @hawkinse 's freepieridge method on a dk1/ headset without tracking or a phone? I have a dk2 clone without positional tracking and have similar issues to yours with positioning being lower than the controller's and about 30 degrees to the right. Hopefully playing with the y setting in the .json and using your tool for rotation will help. I was just curious if you've been able to get positional tracking for your headset with a 3rd move controller. As far as I understand freepieridge requires riftcat software to take free pies free track data and output it as oculus positional data. But won't run without a phone connected. I'd love to be wrong though.
