### ISSUE TITLE
Cannot calibrate tracker pose correctly

### ISSUE THREAD

**Issue by toto5100** [cboulay/PSMoveService#60]
Hello,
I cannot calibrate tracker pose correctly. Everytime, the tracker's location is ok in xz position, but the z position is completely off. Here is my setup : http://imgur.com/0UP5lnZ and http://imgur.com/iTOiw9R
After calibration, here is what i have (the psmove is still attached to the hmd) : http://imgur.com/Aw0fQXJ
The pseye is correctly calibrated, but his estimated position is far too low.

**Comment by HipsterSloth** [comment]
I came across this issue too when I was writing up the camera calibration docs on Friday. The [calibration mat](https://github.com/cboulay/PSMoveService/wiki/Tracker-Pose-Calibration#step-4b-calibration-mat) method now works, but the HMD coregistration method is still broken (issues between using the raw HMD transform data vs. Chaperone Relative transform data from SteamVR ). I'll try and get that fixed by EOD Sunday and get a new binary release up.

**Comment by HipsterSloth** [comment]
Alpha release #2 is up with fixes that should ake care of the issue you were seeing.
