### ISSUE TITLE
PSEye dropping frames and disconnecting

### ISSUE THREAD

**Issue by toto5100** [cboulay/PSMoveService#63]
Hi,
With the lastest release, the pseye is disconnecting after around one minute.
When the PSEye is used (when using the config tool or steamvr), it leads to a crash of the service.
When i'm not using it, the pseye is reconnecting, then disconnecting.

With the alpha 1, i didnt have this problem, but the pseye was often dropping frames (blinking with a green screen). I tried all usb ports, and I still have the problem.
But with test_camera.exe there is no dropped frames.

I also tried to use cleye driver, but the first problem is still there.

**Comment by HipsterSloth** [comment]
There were some changes I made to the PS3EyeCamera code post alpha1 release in an attempt to fix a crash you get adjusting the camera exposure. I suspect this is leading to some new deadlocks cases.  Do you happen to have the log file for the service, usually named `PSMoveService_0.log`. It should be in the same folder that you run `PSMoveService.exe` in. Also do you happen to have visual studio installed? If so, and I know this is a lot to ask, but you would mind attaching to the service in VisualStudio the next time you run it to see if you can catch the crash? If you are unfamiliar with this process and are interested I can walk you through how to do this.

**Comment by toto5100** [comment]
No problem to help you, but i'm very unfamiliar with Visual Studio. I just know how to compile with it but otherwise, i never used it.

**Comment by toto5100** [comment]
Also, here is how it looks like when it crashes : http://imgur.com/ccLE9KG

**Comment by HipsterSloth** [comment]
Here's how you can catch the crash in VS.
1) Open VS as an administrator (Right click on the app icon and select "Run as administrator")
2) Start `PSMoveService.exe`
3) In VS under the "Debug" menu, goto "Debug" > "Attach To Process"
4) Scroll through the list of processes to find, `PSMoveService.exe` and select it.
  ![attach](https://cloud.githubusercontent.com/assets/16793853/16161681/b6d03d3c-3483-11e6-9a31-d9676c49e7a0.png)
5) Wait for the crash
6) Go to "Debug" -> "Save Dump as..." and make sure "Minidump with heap is selected"
7) Zip up the the .dmp file and attach it to this issue. If you built psmoveservice locally add the `PSMoveService.exe` and `PSMoveService.pdb` from `build\src\psmoveservice\Debug` if you built debug or `build\src\psmoveservice\Release` if you built release.

**Comment by toto5100** [comment]
When it crashes, a window opens with this : Unhandled exception at 0x01998DD8 in PSMoveService.exe: 0xC0000005: Access violation reading location 0x00000000.
I think it's because camera is disconnecting when the config tool is still using it, as i'm able to reproduce the same message by manually disconnecting the pseye from its usb port.
Here the dump file : https://drive.google.com/file/d/0B6KwkxK9Par4dGMzbXlkZDI2ODA/view

**Comment by HipsterSloth** [comment]
Ah! Thanks for the tip about manually disconnecting the camera. I was able to repro the crash too by manually disconnecting. 

Of course even with the crash fixed there is still the question of why the camera is disconnecting at all. The service isn't supposed to refresh the camera list unless...
EDIT while type this I just found the bug. There is a flag on the TrackerManager that marks the camera list as needing to be refreshed. 

https://github.com/cboulay/PSMoveService/blob/master/src/psmoveservice/Device/Manager/TrackerManager.cpp#L155

It's only supposed to set this flag on startup or if manually requested. I put the flag in because constantly trying to refresh the camera list every few seconds (like we do for the controller list) turns out not to play nice with active video feeds, as you are experiencing now. 

The bug is that I'm never setting the dirty flag back to false. Whoops! I'm going check in the fix for that now and then make another release.

**Comment by toto5100** [comment]
I'm happy that you found the solution that quickly :+1: 
Nice work !

Also, do you have an idea about why i get frame drops/bad performances when using the camera ? It do not seems to be usb related, as the simple `test_camera.exe` works great. How can I change the camera's framerate, in order to check if it's due to bandwidth ?

**Comment by HipsterSloth** [comment]
New release is up: https://github.com/cboulay/PSMoveService/releases

As for the camera perf issue that was due to bad multi-threading coding on my part. The original crash fix I had in alpha1 was causing the camera update thread to block looking for camera settings changes:

https://github.com/HipsterSloth/PS3EYEDriver/commit/a43942456a99900b538a44243267f5290c9fd960

I later fixed that in alpha2, but then you had the camera reconnection problem so you couldn't test the (hopefully) improved camera perf:

https://github.com/HipsterSloth/PS3EYEDriver/commit/39274b385e01e281cd84094913373c84655b8dbe

Let me know if alpha3 fixes the camera disconnects you were seeing. The perf _should_ be a solid 60fps, but let me know if you see otherwise. If all looks we can mark this issue as resolved.

**Comment by toto5100** [comment]
Yes, all looks good now. About the issue : 

> Calculated linear velocity and acceleration (even low pass filtered data) too noisy. Zero'ing out for now.
I don't know if it's helpful, but when i was using psmove-unity5, to calculate a not too noisy linear velocity in order to throw objects, i was taking the 5 last positions, calculating velocity for each and then averaging. I know it's not right, but it worked okay for throwing objects.

**Comment by HipsterSloth** [comment]
@toto5100 Glad to hear that works! 

I realized I didn't answer a question earlier:

> How can I change the camera's framerate, in order to check if it's due to bandwidth ?

There is currently no way to do this at the moment. It's hard coded to use 640x480@60fps. I'll add a task to expose camera resolution and framerate settings to the tracker settings UI. It'll probably be a while before I get to that, but it's a good suggestion and I don't want to forget it.

> I don't know if it's helpful, but when i was using psmove-unity5, to calculate a not too noisy linear velocity in order to throw objects, i was taking the 5 last positions, calculating velocity for each and then averaging. I know it's not right, but it worked okay for throwing objects.

That's a good idea. That'll probably work better then the low pass filter we're using now. Longer term @cboulay is working on a Kalman filter that will handle smoothing, but that might be a nice stop-gap solution until then.

**Comment by nalf3in** [comment]
Just adding that when your are using the cl eye driver and use the camera preview, you are able to see the camera filter settings set by psmoveservice for tracking the psmove and edit it (including the resolution and fps). The problem is that the psmoveservice always reset the camera settings to his last settings thus erasing the change made with cl cam preview. So if you want a quick fix for cl cam drivers users you could just remove the automatic reseting of the camera settings until you have time for a ''cleaner '' method. 

Finally thanks alot for the fix ! Had the same issue and I thought it was only because I did a wrong driver installation..
