### ISSUE TITLE
Intermittent blanking to green screen while using libusb PSEyeDriver

### ISSUE THREAD

**Issue by picklefart9** [cboulay/PSMoveService#64]
[PSMoveConfigTool_2016_06_18_11_49_36_866.zip](https://github.com/cboulay/PSMoveService/files/321865/PSMoveConfigTool_2016_06_18_11_49_36_866.zip)
My tracker blanks out randomly to a green screen while using libusb and PS3EYEDriver. Unfortunately it seems this issue is the same in alpha 3 as it was in alpha 2, so submitting as an issue. Attached is a video capture of it. Any thoughts?

When I switch to the CLEye driver, I do not have this same screen blanking, but the tracking isn't smooth. If you've never seen this, is there a possibility this is a hardware issue with my PSEye?

.

**Comment by toto5100** [comment]
It happens to me too. It leads to a regular loss of tracking for 1 frame or 2.

**Comment by HipsterSloth** [comment]
So this could be two things. 

1) It's possible that my bug fixes for the crash due to setting exposure while a video feed is running is leading to video frames stalls still. I'm going to be looking into fixing up the video streaming code when I work on adding ps4 camera code sometime next week. 

2) I have also seen this issue in Win10 sometimes when I switch around which port the usb camera is plugged into. Windows gets confused about which driver it should be running (WinUSB vs libusb). It also could be the USB bus that you are plugged into is getting saturated. I think the CLEYE driver defaults to 30fps (which I need to fix), where as the libusb driver is trying to run at 60fps. Try running through the driver cleanup steps here: https://github.com/cboulay/PSMoveService/wiki/Troubleshooting-%28Windows%29#psmoveservices-hangs-shortly-after-starting and maybe try a different USB port. Let me know how that goes.

**Comment by picklefart9** [comment]
Thanks for the feedback. Just to report back regarding the steps you outlined in 2. Went through and uninstalled all allsociated devices. I also used device manager to delete the software. Re-did the setup and made sure it was running with libusb. No dice - intermittent green screen still. Removed all but the required USB devices and plugged into various USB 2 and USB 3 ports, making sure it was using libusb for all of them. No dice again, green screen in every case.

**Comment by Karon1** [comment]
I've got the same green flashes in between frames aswell. What I tried:

uninstalling all drivers from USBDView and trying again -> no success
tried different USB ports and hubs (I tried connecting it to the USB 2 back; 2 front; 3 and 3.1 ports) -> no success

strange thing: every time I plug it into a different port USBDView reports Libusb**K** as driver and I have to change it to libusb0 every time

**Comment by HipsterSloth** [comment]
I've got the same problem reproducing on my machine locally now, so at least I have a reliable test case. I'm going to work on fixing this over the next few days as part of my ps4 camera work.

**Comment by picklefart9** [comment]
One more point, just in case it helps. With Alpha 4.1, whenever the HMD goes to sleep the blanking to green screen stops altogether and I get a smooth image from both of my trackers.

**Comment by pdkkid** [comment]
Im having the same issue, waiting on a pci usb hub to arrive so i can test that instead of the ports on my motherboard

**Comment by HipsterSloth** [comment]
@picklefart9 I have a new release out that might help with the flicker. Mind giving this a try: https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha4.3.

**Comment by picklefart9** [comment]
> @picklefart9 I have a new release out that might help with the flicker. Mind giving this a try: https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha4.3.

Yessir, works! I still get hitches in my feed but no more blanking! Thank you once again for your fantastic work!

BTW is there a donation for you and the other devs, a game of yours to buy, etc.? Just as a way to say thank you.

**Comment by cboulay** [comment]
>BTW is there a donation for you and the other devs, a game of yours to buy, etc.? Just as a way to say thank you.

I'm not sure what @HipsterSloth 's take is on this, but my preference is that you pay it forward. If you're not a coder then there are other options like helping with documentation. @HipsterSloth is pretty excellent with MSPaint but I feel like some of the diagrams could use an upgrade, or be replaced with succinct* and well-labeled videos.

* Just so you don't waste your efforts on videos that I won't link to, please don't do this: "Hey guys, <name> here. Today I'm going to show you how to do this super simple thing that takes 15 seconds, but the video is about 2 minutes long because I need to introduce myself. I also have to introduce this thing, even if there's no chance you could ever come to this video without knowing exactly what this thing is, I still feel the need to tell you what it is. Don't forget to subscribe. Also, I'm typing things out in notepad even though it's hard to read and you can't copy and paste from the video. The text really should go in the video description but then this video wouldn't be unnecessarily long. If you liked this video then you can click through to some of my other overly long explanations of simple things. Don't forget to subscribe."

**Comment by HipsterSloth** [comment]
@cboulay. Ahaha! Tell me how you really feel about youtube streamers :). 
@picklefart9 Yeah I don't think either of us feel really comfortable with the whole donation thing. If coding isn't your jam, any testing, doc writting, or video making is much appreciated.

**Comment by picklefart9** [comment]
On it! I'll work on documentation for you. Give me a few days to put something together and I'll send it to you both.
