### ISSUE TITLE
Failed to start controller stream!

### ISSUE THREAD

**Issue by demonixis** [cboulay/PSMoveService#81]
Hi,

I'm trying to use two PSMoves and I have few issues.

My two controllers are paired to Windows, one is magenta and the other is cyan. I have changed the color of the first to cyan and tried to calibrate the tracker using the calibration mat. It doesn't works after few tries, I wasn't able to start the color calibration. I have this message.

![image](https://cloud.githubusercontent.com/assets/1017126/16408618/e1d22560-3d19-11e6-8d35-9887b357ae11.png)

Do you know what's happened? Can I solve it?

**Comment by zelmon64** [comment]
@demonixis The tracker calibration only works with magenta (because it assumes the first default PSMove is magenta). Just restart the server and re-run calibration and it should return to magenta. Additionally, when you ran the color calibration did you check to see if the masks are set correctly? The mask for each PSEye has to be able see magenta otherwise the tracker calibration will never work correctly.

**Comment by demonixis** [comment]
Hi,

Well it works again but the second PSMove is cyan and I can't change it. So I'm limited to one psmove?

**Comment by zelmon64** [comment]
The tracker calibration only needs to be done once. It gathers the information for where the PSEyes are in real space. Then to get more PSMoves to work it's just a matter of ensuring the masks are all working in the color calibration for each PSEye.

**Comment by demonixis** [comment]
Ok I've the two controllers working now but they are not in the correct place. The PS3Eye is physically located on the top of my DK2 tracker and it's on the right in SteamVR. The controllers are not centered to the HMD view.
