### ISSUE TITLE
Add option to have another move controller colored while calibrating colors

### ISSUE THREAD

**Issue by pdkkid** [cboulay/PSMoveService#95]
Adding an option to have a second move controller display a color, while calibrating a trackers color identification would help alot with the colors conflicting with each other. For example, when i was calibrating magenta, for some reason my second controller stayed cyan, and in the 'masked view' the controller easily saw both colors, causing a conflict when tracking. Adding an option to have a second controller be able to cycle colors would help when calibrating so the camera only picks up a single color, instead of accidentally picking up multiple colors. If this explanation dident make any sense, i can recreate the issue and post some screenshots if necessary.

**Comment by cboulay** [comment]
You were perfectly clear and that's a good idea. One of the options for the second controller could even be to rotate through the other colours.

But, probably the better solution is to simply change the colour of the second, third, etc controllers using the config tool. Off the top of my head I'm not sure if setting the controllers colours in the config tool is possible and if it persists across service restarts, but that should be done at some point.

**Comment by HipsterSloth** [comment]
Turns out we definitely need different color filter settings between the PSMove and the DualShock4. I just added a feature for allowing you to opt-in to per-controller-per-tracker color filter settings. In the tracker settings menu you can now select which controller you want to set the color filter for (or pick "all") which has the same behavior as before. Any controller that doesn't have the color filter set will fallback to the general filter for that tracker. This fix will be in the next release. I'll close this issue then.

**Comment by HipsterSloth** [comment]
I just published a [release](https://github.com/cboulay/PSMoveService/releases/tag/v0.9-alpha5.0) with these changes. I'm marking this issued as resolved. If anything comes up please feel free to start a discussion on the newly opened forum: https://groups.google.com/forum/#!forum/psmoveservice
